### ISSUE TITLE
Restore regular compatibility bumps and validation.

### ISSUE THREAD

**Issue by Sancus** [thundernest/addons-server#1]
Thunderbird hasn't had an automated compat bump in a while, see https://bugzilla.mozilla.org/show_bug.cgi?id=1407947. We may be able to resurrect it, or maybe not.

**Comment by mkmelin** [comment]
I doubt we should do compatibility bumps anymore. Without updates the add-on isn't likely to work.

**Comment by Sancus** [comment]
> I doubt we should do compatibility bumps anymore. Without updates the add-on isn't likely to work.
The idea was that we would write a validator patch so that it would detect which ones can work and which can't for TB60. Which is probably possible. And what about future versions? Without compat bumps, authors basically have to change their compatibility manually for each version, even if there's no breaking changes.

The compat bumps alleviate that. Whether it's worth the time or not is a different question. We used to do those patches regularly several years ago. 

If you'd rather we not spend the time on it, and expect add-on authors to do handle it manually, we can just close this. I don't care about it much either way, personally.

**Comment by mkmelin** [comment]
Tb60 is already almost out. For TB68, I doubt there are many add-ons that wouldn't require update. 
So let's leave it for add-on authors.
