### ISSUE TITLE
Can't manage my add-ons

### ISSUE THREAD

**Issue by dillenger** [thundernest/addons-server#100]
All (or nearly all) pages on https://addons.thunderbird.net/en-US/developers/addons now take me to an Oops page:

Oops! We had an error.
We'll get to fixing that soon.

You can try refreshing the page, or head back to the Add-ons homepage.

Refreshing doesn't work, unfortunately.

**Comment by Sancus** [comment]
I can only reproduce this for lightweight themes, which is expected, as they're no longer supported and no longer display on the site.

Not the best UI presentation, but I will delete them eventually so they'll be gone from your profile.

The management links for your actual addons, eg [Phoenity Buttons](https://addons.thunderbird.net/en-US/developers/addon/phoenity-buttons/edit), [Phoenity Shredder](https://addons.thunderbird.net/en-US/developers/addon/phoenity-shredder/edit), etc seem to work fine.

You should be able to upload WE theme versions of all these by downloading them from AMO, [adding an 'id' in the applications object, as noted in the documentation](https://developer.thunderbird.net/add-ons/web-extension-themes#use-a-manifest-json-file), and then uploading on ATN. 'browser_specific_settings' is not supported for us right now but will be in the future.

**Comment by dillenger** [comment]
Weird, I can log in on https://addons.thunderbird.net/en-US/developers/ 
and it shows 3 of my add-ons, but as soon as I click any Edit Listing 
<https://addons.thunderbird.net/en-US/developers/addon/profileswitcher2/edit> 
link or the View All Submissions 
<https://addons.thunderbird.net/en-US/developers/addons> link, I get the 
Oops page.
There may be something wrong with my profile, this started after 
ProfileSwitcher2 was rejected, perhaps there is a link.

**Comment by Sancus** [comment]
I set the state of ProfileSwitcher2 to Disabled, did that help?

**Comment by dillenger** [comment]
Yes!

It took a few minutes, but now it is working again.

Many thanks.

**Comment by Sancus** [comment]
OK. I'm actually going to re-enable LWT editing for now so that other developers don't run into these errors. Will need to delete them before I turn that off again.

Thanks for the quick responses, it made debugging much easier :)
