### ISSUE TITLE
Update "Get Add-ons" Page

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/addons-server#104]
The Get Add-ons page that you can load within Thunderbird seems dated and low on content.

We should update that page to look and feel modern, but also present users with more content beyond the Featured Add-ons.

**Comment by Sancus** [comment]
Yes, doing an external rewrite on this is something that I want to do. We should not attempt this in the addons-server code. We should build a new discovery pane that uses the API. This is a long term project, among other things, we'll need to see if we can add it to Pontoon and get l10n done for any copy, in addition to pulling in Alessandro for design help.

One major concern is that Mozilla is removing the ability to load a remote page for this in some future version, likely before 76. So we may need to consider adapting or building our own in-client discovery pane.

**Comment by ryanleesipes** [comment]
I really like the idea of a new discovery pane that uses the API. In fact, using the API to create a native experience within Thunderbird isn't a bad idea IMO.

**Comment by wsmwk** [comment]
> One major concern is that Mozilla is removing the ability to load a remote page for this in some future version, likely before 76. So we may need to consider adapting or building our own in-client discovery pane.

The release numbers have changed recently https://wiki.mozilla.org/Release_Management/Calendar but perhaps the timing hasn't, so that removal will come soonish :)   ~Q1 2020 or early Q2?    I'd suggest we'd want this to be in our beta some time in Q1

**Comment by Sancus** [comment]
Since we have decided to use the Toolkit discovery pane and it's [active in Nightly and Beta now](https://bugzilla.mozilla.org/show_bug.cgi?id=1600923) this is resolved.
