### ISSUE TITLE
Unable to log in with new Email address [Resolved]

### ISSUE THREAD

**Issue by Frank-Lion** [thundernest/addons-server#107]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

The below link I found on the Net describes exactly the problem I'm having -

https://github.com/mozilla/addons/issues/836

As I soon will not be using my original Email address
(....@tiscali.co.uk) I made my gmail account my primary Email.

### What happened?
Now, I cannot log in and receive only a 'detail":"Internal Server
Error' message.

### What did you expect to happen?
To log into my Developer account..

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
Please email me at `sancus at thunderbird dot net` from your old email with the new one and I'll fix the account manually.

**Comment by Sancus** [comment]
This should now be resolved. Removed previous comment that showed my email to avoid any potential spam harvesting.

**Comment by Frank-Lion** [comment]
Issue now resolved. My thanks to Sancus.

**Comment by aramaicus** [comment]
I'm experiencing the same issue. Could you assist me, please, @Sancus ?
