### ISSUE TITLE
Add-on Collections

### ISSUE THREAD

**Issue by charliegc4** [thundernest/addons-server#112]
### Describe the problem and steps to reproduce it:
Open https://addons.thunderbird.net/en-US/thunderbird/collections/ and browse collections

### What happened?
There are only two collection listed

### What did you expect to happen?
I expected to see many collections.

### Anything else we should know?
No.

**Comment by Sancus** [comment]
I don't think these even work properly anymore, and as far as I know, they've been abandoned as a feature by AMO devs, so this is a wontfix.
