### ISSUE TITLE
missing link to Czech Language Pack

### ISSUE THREAD

**Issue by nesnera** [thundernest/addons-server#114]
### What happened?
Missing link to Czech Language Pack at https://addons.thunderbird.net/en-US/thunderbird/language-tools/.
### What did you expect to happen?
Something like https://addons.thunderbird.net/en-US/thunderbird/addon/english-us-language-pack-thund/. The appropriate Language Pack exists e.g. https://archive.mozilla.org/pub/thunderbird/releases/68.1.1/linux-x86_64/xpi/cs.xpi

**Comment by Sancus** [comment]
https://addons.thunderbird.net/en-US/thunderbird/addon/tb-language-pack-czech-cs/
