### ISSUE TITLE
Remove themes from Thundbirds in app recommendations page.

### ISSUE THREAD

**Issue by MadMattAu** [thundernest/addons-server#115]
Currently Thunderbird is still displaying a complete themes selector in the recommended tab on Thunderbird 68. in the addon manager.  I understand this is hosted at addons.thunderbird.net

My understanding is that complete themes are basically dead in Thunderbird 68 unless they are built in,  to the point the monorail theme has been released as a standard add-on.  Perhaps this block needs to be hidden for version 68 users.

**Comment by wsmwk** [comment]
@Sancus @darktrojan is this possible?

**Comment by Sancus** [comment]
That page is deprecated since 78 and will probably stop working with future ATN updates in any case, not making any changes to it.
