### ISSUE TITLE
serve json update manifests on versioncheck for TB62+ only

### ISSUE THREAD

**Issue by Sancus** [thundernest/addons-server#12]
Firefox has supported this since 45, and [there is a patch](https://github.com/mozilla/addons-server/commit/131c8f22db98c6a09784202fc43b8c3cbb536025#diff-10cd395cf71c18328c863c08e78f3fd0) to serve manifest.json to Firefox-only. This is going to need modification to serve to TB62+ only, because prior versions do not support manifest.json.

E: update manifests and manifest.json are two different things.

**Comment by oeekker** [comment]
I think you mix manifest.json with updates.json (which can be named by any name btw). The first is for add-ons, the latter for update checks.

**Comment by Sancus** [comment]
Maybe, I assumed they were the same because the patch above call them update manifests. Unfortunately the information on this is scattered all over the place and I really don't have time to try to figure out how all of it works.

If someone can tell me what version of Thunderbird won't break if versioncheck.addons.thunderbird.net serves JSON to Thunderbird instead of RDF, that's all the information that I need. The answer is apparently some version later than 52.*

If the answer is indeed still TB62+ then we're back to square 1.

**Comment by Sancus** [comment]
This needed immediate fixing due to https://bugzilla.mozilla.org/show_bug.cgi?id=857458#c18 since 67/68 no longer support the XML RDF format for update manifests.

I set up a staging versioncheck server and extensively tested TB60 and 67b3, both work fine with the new JSON format, so in revision https://github.com/thundernest/addons-server/commit/fda2ba48c717c23052aae20b37f194b1df17b6b8 it was enabled. This has been deployed.

The XML RDF format code remains and is enabled for SeaMonkey alone for now.
