### ISSUE TITLE
Add-on failed validation with 1 error

### ISSUE THREAD

**Issue by EdgardoRios** [thundernest/addons-server#122]
### Describe the problem and steps to reproduce it:
Hello, I am trying to upload a new version of an Add-on to Thunderbird Add-ons Server, and it failed validation with 1 error.

(Please include as many details as possible.)
Steps:
1. Go to Thunderbird Add-ons page. [1]
2. Login and go to 'Tools/Manage My Submissions'.
3. Go to Submit a New Version.
4. Click on 'Select a file...' button.
5. Pick the new file version (*.xpi).
6. Valition and after that, the following error message:
Your add-on failed validation with 1 error.
GUID is required for Thunderbird Mail Extensions, including Themes.

### What happened?
Validation error.

### What did you expect to happen?
Validation, no errors and upload the new version of the file to Add-ons page.

### Anything else we should know?
Yes, this is just a spell checker dictionary, it works just fine in Firefox Add-ons page. [2]
I took a look to 'See full validation report' and could not find an error there.

[1] [Thunderbird - Spanish (Mexico) Dictionary](https://addons.thunderbird.net/en-us/thunderbird/addon/spanish-mexico-dictionary/)
[2] [Mozilla - Spanish (Mexico) Dictionary](https://addons.mozilla.org/en-US/firefox/addon/spanish-mexico-dictionary/)

(Please include screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/18619087/72916781-3d8e7380-3d08-11ea-81d2-d1e4f6c89282.png)

**Comment by Sancus** [comment]
Yes, you need to have a GUID in your dictionary. Firefox Add-ons are different, because they use signing and we don't.
```"applications": {"gecko": {"id": "somekindaguid@example.net"}}```

The above structure needs to be present in your dictionary's manifest.json, and it has to be 'applications' not 'browser_specific_settings' as well.

**Comment by EdgardoRios** [comment]
Thank you! Problem solved. 🙂
