### ISSUE TITLE
Unable to log in to Dev Panel.

### ISSUE THREAD

**Issue by Frank-Lion** [thundernest/addons-server#125]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Trying to log in here - https://addons.thunderbird.net/eN-US/seamonkey/addon/metal-lion-sea-monkey/ just produces endless loading here -
https://accounts.firefox.com/authorization?action=signin&scope=profile&state=54416515bab71121c6d5aee1ac0d93387f6a50a086151f1541c448c6cab3b327%3AL2VOLVVTL3NlYW1vbmtleS9hZGRvbi9tZXRhbC1saW9uLXNlYS1tb25rZXkv&redirect_url=https%3A%2F%2Faddons.thunderbird.net%2Fapi%2Fv3%2Faccounts%2Fauthenticate%2F&client_id=25691f3bf98f8ea8

### What happened?
Endless loading

### What did you expect to happen?
To be able to see a log in screen, at the least.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
I can't reproduce this, so it must be an issue related to your specific account. Have you changed your Firefox Account email recently? Can you sign in on accounts.firefox.com? On AMO?

**Comment by Frank-Lion** [comment]
Hi, no, nothing has changed on my account and the endless loading is happening with both SeaMonkey and M$ Edge browsers.

I then realised - this is a **Mozilla** related website - so I used a VPN to the USA and a Chrome UA and was then instantly able to log in.
