### ISSUE TITLE
Is it possible to merge extensions?

### ISSUE THREAD

**Issue by dillenger** [thundernest/addons-server#126]
Is it possible to merge extensions?
Possibly by redirecting update requests from one extension to another?

I'm asking because I want to merge my version of Edit Email Subject:
https://addons.thunderbird.net/en-US/thunderbird/addon/editemailsubject/
back into the original, which has recently been revived and is currently nearly identical:
https://addons.thunderbird.net/en-US/thunderbird/addon/edit-email-subject/

**Comment by Sancus** [comment]
No, there's no way to do that. You can delete an extension, that's about it. That won't, of course, redirect anyone who previously used it.

This kind of thing has been requested a few times but it's really complicated to do correctly and Thunderbird has no support for it on the client side. Silently redirecting update requests from one add-on to another one is not something that would be usable in many cases.

If we ever do implement anything like this it'll be announced on tb-planning, but I wouldn't expect it to happen, there are no current plans to do it.

**Comment by Sancus** [comment]
I should add, the way we've handled this for ImportExportTools is to simply add a pointer link at the top of the description to the new add-on, and wait for people to switch over manually. That's the best you can do. They will switch over gradually if you do not maintain version support for the older add-on.

**Comment by dillenger** [comment]
Ok, thanks, too bad, I'll try the ImportExportTools way.
