### ISSUE TITLE
check on commands api still based on FF<63?

### ISSUE THREAD

**Issue by opto** [thundernest/addons-server#130]
### Describe the problem and steps to reproduce it:
Trying to upload an addon with commands, e.g. ctrl-alt-h, addon is working in 76

### What happened?
addon is rejected because commands are formed wrong. It seems only shift is allowed as second modifier. That is what was allowed for FF<63.
### What did you expect to happen?
allow upload
### Anything else we should know?
more info on topicbox:  https://thunderbird.topicbox.com/groups/addons/Tff9f2582547c157c/addon-doesnt-pass-atn-check
that link includes error message and link to MDN (FF) explaining changes in commands syntax before/after FF63

**Comment by Sancus** [comment]
This is probably related to https://github.com/thundernest/addons-server/issues/73 but not 100% sure so I'll leave it open until I have time to look at it.

**Comment by opto** [comment]
thanks. What I forgot to mention: because the commands respective the addon is rejected (error, not warning), this totally limits the number of available shortcuts as seen over all mailextensions available on ATN. Worse even, because the FF api does not allow to request which shortcuts are taken, and a few of ctrl-shift are taken by TB itself.

**Comment by Sancus** [comment]
This should be resolved now by https://github.com/thundernest/addons-server/compare/467b109eaca31690aff9ada0144e8b767c5b0932...562d838402244e64ba705f881588bce715d9727d - reopen if not.
