### ISSUE TITLE
warnings on nonexisting functions at mailExtension upload

### ISSUE THREAD

**Issue by opto** [thundernest/addons-server#131]
you want me to report that and keep track on that here?

what I definitely remember is MailTabs.setQuickFilter.
There was more, I can add that next time if you want. (mailTabs.getSelectedMessages )

The addon was accepted and is working in 68 and 76, so it is more a cosmetic issue.

Klaus

**Comment by Sancus** [comment]
This is a dupe of https://github.com/thundernest/addons-server/issues/73
