### ISSUE TITLE
WebExperiment upload fails

### ISSUE THREAD

**Issue by benbucksch** [thundernest/addons-server#132]
I'm trying to [submit a new version of Owl](https://addons.thunderbird.net/developers/addon/owl-for-exchange/versions/submit/). Owl is a WebExtension with WebExperiments, which are necessary due to its nature.

Immediately after the XPI uploaded, I get the error message:
```
Your add-on failed validation with 1 error.
Sorry, we couldn't load your WebExtension.
```

![grafik](https://user-images.githubusercontent.com/1907525/80268651-6593c700-86a9-11ea-8c31-5c10ec2f62d6.png)

In the details, it says:
```
Validation was unable to complete successfully due to an unexpected error.
```

![grafik](https://user-images.githubusercontent.com/1907525/80268670-95db6580-86a9-11ea-8993-8539b2859209.png)

So, the addon server seems to barf while validating the XPI.

I have no new structural changes in the new version. To double-check, I checked out the code for the last version that's currently released and public and created a new XPI with a new version number, but otherwise identical, and uploaded that XPI, and it comes back with the same error. So, this is clearly a change in the addons server and not due to my addon.

I need to quickly publish a new version, because it contains hotfixes for problems that end users see.

**Comment by Sancus** [comment]
I restarted the validation servers and it looks like it's fixed this, go ahead and try again.

**Comment by benbucksch** [comment]
Yes, it works now.

Thanks, sancus! :-)
