### ISSUE TITLE
[Review Tools] Error on Notify me about new listed versions

### ISSUE THREAD

**Issue by erosman** [thundernest/addons-server#133]
For a very long time, "Notify me about new listed versions" has been broken (I am trying to remove the tick).

The XHR (`/api/v4/reviewers/addon/****/unsubscribe/`) gets `401 Unauthorized` although I am able to review.

**Comment by Sancus** [comment]
Have you tried logging out and then in again?

**Comment by erosman** [comment]
> Have you tried logging out and then in again?

No.... I tried it now and it seem that login in/out fixed the problem.
Thank you.
