### ISSUE TITLE
German Text/Translation on addons.thunderbird.net/de/thunderbird/collections/

### ISSUE THREAD

**Issue by dvschuetz** [thundernest/addons-server#134]
The german text says: "Sammlungen machen es einfach, Ihre Lieblings-Add-ons zu verwalten und Ihren perfekt angepassten **Browser** mit anderen zu teilen." meaning: "... sharing your experience with your **browser**...".
But Thunderbird is not a browser, it is an **email-client**.
See here; [addons.thunderbird.net/de/thunderbird/collections/](https://addons.thunderbird.net/de/thunderbird/collections/)

![grafik](https://user-images.githubusercontent.com/5382362/80858182-ea598480-8c57-11ea-81d4-bfae37fbdda3.png)

**Comment by Sancus** [comment]
These minor string issues will be resolved one day when we do our own front-end, but there's no point in filing them all as we are aware the current website references firefox/browser in a lot of places and it's not practical to change them due to breaking localizations.
