### ISSUE TITLE
Unable to configure in Thunderbird

### ISSUE THREAD

**Issue by dsgiigh** [thundernest/addons-server#136]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
Installed in Thunderbird 68.7 (Ubuntu 20.04), but unable to configure when replying to the welcome email. The "AutoCrypt" button/drop-down doesn't appear.

### What did you expect to happen?
Expected to see the button.
![Screenshot from 2020-05-24 18-14-32](https://user-images.githubusercontent.com/804184/82750337-7b042a00-9dea-11ea-8d0c-03aa86a59738.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
This isn't a bug with the website. Please don't file bugs about add-ons. You'll have to contact the addon author about this, the Thunderbird team doesn't have anything to do with Autocrypt.
