### ISSUE TITLE
Unexpected search words user experience

### ISSUE THREAD

**Issue by DGrothe-PhD** [thundernest/addons-server#137]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Unexpected search result
### What happened?
I typed "green" in the Search for themes field.
I got plenty of results, all about "Greek".
### What did you expect to happen?
To get results that have anything to do with "green" - or none if there aren't.
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by DGrothe-PhD** [comment]
Possible solution: to have a link saying "Did you mean Greek?"

**Comment by Sancus** [comment]
Sorry but this isn't a bug, there just aren't very many add-on results for 'green', so it guesses at what you might mean, it's the similar logic to what you get if you do this on Google.

If you are looking for a Theme(for which there are many 'green' results) you should search in the Theme section of the site, by clicking 'Themes' at the top before searching: https://addons.thunderbird.net/en-US/thunderbird/search/?q=green&cat=themes
