### ISSUE TITLE
Lint problems uploading new ca dictionaries

### ISSUE THREAD

**Issue by toniher** [thundernest/addons-server#139]
I'm uploading some new ca dictionaries (https://github.com/Softcatala/catalan-dict-tools/releases/tag/v3.0.5) and I get the following lint errors so I cannot proceed:

```
Your add-on failed validation with 2 errors.

    GUID is required for Thunderbird Mail Extensions, including Themes.
    The manifest contains a dictionary but no id property.
```

Using Firefox Addons site there is no problem and testing with https://github.com/mozilla/addons-linter/ everything seems OK.

Any idea?

**Comment by Sancus** [comment]
You need an `applications` or `browser_specific_settings` block in your manifest.json as documented: https://developer.thunderbird.net/add-ons/examples/web-extension-themes

We don't sign add-ons unlike Firefox so it won't work without specifying an ID.
