### ISSUE TITLE
Update linter to prevent validation fails on new js syntax

### ISSUE THREAD

**Issue by alta88** [thundernest/addons-server#140]
The [updated linter pr](https://github.com/mozilla/addons-linter/pull/3181) for AMO seems to have been merged into master. Is this automatic for ATN or is special action necessary? Because no extension updates possible for a while now..

**Comment by Sancus** [comment]
Everything on ATN requires special action, we're on an ancient version of addons-server because Thunderbird support was completely removed from AMO long ago.

Updating the linter will happen eventually though, yes.

**Comment by Sancus** [comment]
This is really a duplicate of https://github.com/thundernest/addons-server/issues/121 but that is less clear so I'll close the other one instead.

**Comment by alta88** [comment]
Until it's updated, I strongly request the linter be disabled. It's not a correct tradeoff to prevent extension updates for this nice to have, not must have, feature.

**Comment by Sancus** [comment]
Linter is now at 2.10.0 since https://github.com/thundernest/addons-server/commit/b05da82c3fc37688301848105f749984a13c0277
