### ISSUE TITLE
SeaMonkey: "Dictionaries & Language Packs" needs to become "Dictionaries"

### ISSUE THREAD

**Issue by RainerBielefeld** [thundernest/addons-server#144]
Currently [Dictionaries & Language Packs](https://addons.thunderbird.net/en-US/seamonkey/language-tools/) lists only ond Lange Pack additionally to the Dictionaries:  [Deutsch (DE) Language Pack for SeaMonkey 2.49](https://addons.thunderbird.net/en-US/seamonkey/addon/deutsch-de-language-pack-for-s/) by KaiRo. That'snot a good Idea. SeaMonkey Language packs are Version related, and so it is not useful to list that language pack on the Dictionaries page.

Language pack download is limited to the[ SeaMonkey Project](http://www.seamonkey-project.org/) [Release pages](http://www.seamonkey-project.org/releases/).

*Please drop That Language pack* (of obsolete SeaMonkey Version 2.49) from That Add-On download page and rename page to "Dictionaries"

Please also see "[Bug 1256557](https://bugzilla.mozilla.org/show_bug.cgi?id=1256557) Link target for 'Download More Dictionaries' offers German Language Pack for SeaMonkey 2.39"

**Comment by Sancus** [comment]
I removed the outdated DE language pack from the listing for you.

I'm not going to change the strings because it would break localizations and we don't have any way to do new localizations for ATN. I think people will be OK figuring out there are no language packs there based on the fact that none are listed.

**Comment by RainerBielefeld** [comment]
@Sancus:
Thx, I agree with your arguments and I can live with that solution.
