### ISSUE TITLE
Cardbook birthdays gone

### ISSUE THREAD

**Issue by Rolfi56** [thundernest/addons-server#149]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
thunderbird addon cardbook
birthdays in all adresses gone

### Anything else we should know?
restoring from vcf-file does not produce birthday data too

**Comment by Sancus** [comment]
Please contact the addon author for support, this bug tracker is for issues with the website. Not with individual add-ons. [Cardbook provides a support email in their listing](https://addons.thunderbird.net/en-US/thunderbird/addon/cardbook/).
