### ISSUE TITLE
Redirect reviewers.addons.thunderbird.net to addons.thunderbird.net

### ISSUE THREAD

**Issue by kewisch** [thundernest/addons-server#15]
I have a few scripts that assume `reviewers.$AMO_HOST` is reachable. Can you make it so that reviewers.addons.thunderbird.net is just a CNAME to addons.thunderbird.net? This would probably make my scripts happy.

**Comment by Sancus** [comment]
https://reviewers.addons.thunderbird.net is now live and seems to 301-redirect to ATN just fine.

Happy scripting!
