### ISSUE TITLE
DropBox

### ISSUE THREAD

**Issue by SharkyCA** [thundernest/addons-server#150]
Followed a link from site as I am trying to paste code into auth for Thunderbird Vers 68.12.1 and paste does not work!

### Describe the problem and steps to reproduce it:
[https://addons.thunderbird.net/en-US/thunderbird/addon/cloudfile-provider-for-dropbox/](url)
(Please include as many details as possible.)

### What happened?
Page returned "Couldn't find" https://addons.thunderbird.net/en-US/thunderbird/addon/cloudfile-provider-for-dropbox/
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
I don't understand what your issue is, sorry. There is no addon at that link.

If you have an issue with this addon: https://addons.thunderbird.net/en-US/thunderbird/addon/filelink-provider-for-dropbox/ this isn't the place to get add-on support, it's for issues with the website.

**Comment by Sancus** [comment]
This seems like it's probably a support issue with the FileLink system, you can request support on https://support.mozilla.org/en-US/questions/new/thunderbird
