### ISSUE TITLE
addons-linter needs updating to support optional chaining and other features available in TB 78+

### ISSUE THREAD

**Issue by Standard8** [thundernest/addons-server#151]
### Describe the problem and steps to reproduce it:

I tried uploading a version of conversations that had [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in some of the javascript files. This is available in Thunderbird 78+.

### What happened?

Validation failed:

```
Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
content/messageDetails.js line 50 column 34
```

### What did you expect to happen?

No failures, this is now valid javascript.

### Anything else we should know?

addons-linter added optional chaining support in 2.x: https://github.com/mozilla/addons-linter/releases/tag/2.0.0

Would be good to get that updated, so that we can support all new features.

**Comment by Sancus** [comment]
This has been resolved in https://github.com/thundernest/addons-server/compare/467b109eaca31690aff9ada0144e8b767c5b0932...562d838402244e64ba705f881588bce715d9727d and deployed to production.
