### ISSUE TITLE
Sort out language pack listings

### ISSUE THREAD

**Issue by Sancus** [thundernest/addons-server#152]
https://addons.thunderbird.net/en-US/thunderbird/language-tools/

Some language packs do not have listings when they should, and others are distributed by Mozilla but not owned by a Mozilla account. In addition, a number of language packs have slugs(link names) that are longer than the current 30 character limit. We should redo the slugs so that they're always a standard format of 'tb-language-pack-{name}-{code}' ie tb-language-pack-french-fr.

**Comment by Sancus** [comment]
To add a language pack:
1) Upload it using an admin account.
If you get 'duplicate add-on ID' that likely means there was a previous, deleted listing. Need to go in the admin panel and change the GUID for that add-on to something else so you can reuse the id.
2) Use 'general' category, make sure the slug matches tb-language-pack-{name}-{code}.
3) Change "target locale"(at the bottom of the add-on's admin profile) to the appropriate language code.
4) Remove the admin account and add the Mozilla account(addons@thunderbird.net) as owner in the developer UI.

**Comment by justdave** [comment]
Can't self-assign me on this, but I've been working on this.

**Comment by Sancus** [comment]
Lets do tb-langpack-{code} so it doesn't go over the 30 char limit ever.

**Comment by Sancus** [comment]
This is done, great!
