### ISSUE TITLE
Addons-Linter: Insufficient granularity for “valid application versions”

### ISSUE THREAD

**Issue by Qeole** [thundernest/addons-server#153]
### Describe the problem and steps to reproduce it:

I tried to validate a Thunderbird add-on, with `strict_min_version` set to `"78.4"` in my manifest. I do _not_ want `"78.0"`, because the MailExtension API I'm working with was introduced in Thunderbird 82 and backported to 78.4 only, so my add-on would not work with version 78.0 for example.

### What happened?

```
❌ Your add-on failed validation with 1 error.
    Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?
```

As I understand from https://github.com/mozilla/addons-linter/issues/1848, Mozilla's linter attempts to match the provided number with [a list of known versions](https://addons.mozilla.org/en-us/firefox/pages/appversions/), and `78.4` does not seem to be in that list. I could not tell whether the Thunderbird version of the linter picks the list of known versions for Firefox or another list proper to Thunderbird.

[On another note, the new API (`messageDisplayScripts`) was not recognized by the linter and triggered a warning. But I can live with warnings.]

### What did you expect to happen?

I would expect `"78.4"` to be recognized as a version and to be accepted as a valid input for `strict_min_version`.

The only way I have to publish the add-on at the moment seems to be to use `"78.0"` instead, but this means that all people with Thunderbird 78.[0-3] will get a broken add-on.

### Anything else we should know?

* [I would have filed this issue on [the addons-linter repo](https://github.com/mozilla/addons-linter), but issues are disabled.]
* Issue originally and erroneously filed for Mozilla's addons-linter repo https://github.com/mozilla/addons-linter/issues/3416.

**Comment by Sancus** [comment]
I don't normally add minor versions because there isn't usually a reason to restrict installs to them, however, in this case there. So I have added 78.4.0 -- you have to use the full version not just 78.4, but it should work now.

**Comment by Qeole** [comment]
Thank you! I could indeed update the add-on with a minimum version requirement of `78.4.0`.
