### ISSUE TITLE
Addons-Linter: Fix link to GitHub repository for the linter

### ISSUE THREAD

**Issue by Qeole** [thundernest/addons-server#154]
On failure to validate a Thunderbird add-on, the linter prints a message with a link directing to the GitHub repository for the linter:

```
We have enabled a new linter to process your Add-on. Please make sure to report any issues on GitHub
```

This link actually points to: <https://github.com/mozilla/addons-linter/>, which is not the correct version for ATN. Instead, the fork at <https://github.com/thundernest/addons-linter/> is used. Misled people may end up filing issues in the wrong repository. Fixing the link could prevent that.

However, note that issues are currently disabled for the latter repository, so I'm unsure if the link should point to that one or to some other place.

**Comment by Sancus** [comment]
The fork is NOT currently in use -- we use the standard Mozilla linter. I don't know if this bug is fixable. If this string is in the linter itself, it's not fixable currently. It's not clear if we will use a fork eventually or what exactly.

**Comment by Qeole** [comment]
For what it's worth I could not find the string in the addons-linter repository itself (on a quick GitHub search).

Understood, thank you for your answer!

**Comment by Sancus** [comment]
I found the string in addons-server code in fact, so easy fix. This will be deployed tomorrow.
