### ISSUE TITLE
SmartTemplate4 and Thunderbird 78.4.0.

### ISSUE THREAD

**Issue by studio-creation** [thundernest/addons-server#155]
I updated Thunderbird today 
but now my SmartTemplate4 is not working anymore.
Will there be an update for the Addon, too?

**Comment by RealRaven2000** [comment]
> I updated Thunderbird today
> but now my SmartTemplate4 is not working anymore.
> Will there be an update for the Addon, too?

Yes, see: https://github.com/RealRaven2000/SmartTemplate4/issues/69

the very latest beta is available here (as of today):
https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre60

**Comment by studio-creation** [comment]
It worked. Thank You

**Comment by Sancus** [comment]
Thanks for responding @RealRaven2000. This isn't a website issue, so I'm closing it.

Issues with specific add-ons should be addressed with their authors and not filed here.
