### ISSUE TITLE
Downloads of addons and themes not working: HTTP 404 error

### ISSUE THREAD

**Issue by herrminni** [thundernest/addons-server#156]
### Describe the problem and steps to reproduce it:
Downloading of Thunderbird Addons from inside Thunderbird or the website "https://addons.thunderbird.net" all are not not working and lead to HTTP 404 - not found error.

This is a common issue currently (2020-12-20 at 01:04 CET) and concerns all addons and themes, not just a single one.

**Comment by jmozmoz** [comment]
I can confirm this problem

**Comment by Sancus** [comment]
confirmed; working on it.

**Comment by Sancus** [comment]
This should be fixed now.

**Comment by herrminni** [comment]
Thank you @Sancus! 
I can confirm the downloads are working again. Thanks!
