### ISSUE TITLE
"Font and Size Changer" Addon

### ISSUE THREAD

**Issue by berlinone** [thundernest/addons-server#159]
### Describe the problem and steps to reproduce it:
I am trying to find a Menu "Font and Size Changer" Addon. None of them work with the newest version and I cant find any helpful solution on Google or Forums.

### What happened?
Link to Addon doesn't exist

### What did you expect to happen?
Download an Addon

### Anything else we should know?
https://addons.thunderbird.net/en-US/thunderbird/addon/theme-font-size-changer-for-tb/reviews/1026579/

**Comment by Sancus** [comment]
This isn't the bug with a website. We don't provide support for individual add-ons. [This review](https://addons.thunderbird.net/en-US/thunderbird/addon/theme-font-size-changer-for-tb/reviews/1165129/) suggests an alternative add-on(browseintab). If that isn't sufficient for your needs, your only option is to contact the add-on author.
