### ISSUE TITLE
ATN does not know about 78.6.* and 78.7.* which does not allow to set those versions as minimum TB requirement

### ISSUE THREAD

**Issue by jobisoft** [thundernest/addons-server#161]
### Describe the problem and steps to reproduce it:
Trying to set the min supported version of an add-on to 78.7.

### What happened?
Drop-down menu in the add-on settings on my ATN profile page does not have any values for TB78 beyond 78.5.

### What did you expect to happen?
Drop-down menu in the add-on settings on my ATN profile page should include all released versions, like 78.6 or 78.7.

### Anything else we should know?
I made a screenshot:

![image](https://user-images.githubusercontent.com/5830621/108098126-4a080b80-7083-11eb-9d17-dee0d7d5eb39.png)

**Comment by Sancus** [comment]
I don't normally add minor versions since they don't usually contain changes relevant to add-on development. Versions need to be manually added. I've added 78.6.0 and 78.7.0.

**Comment by jobisoft** [comment]
Thanks for your help. Do you want me to ping you, when we have backported relevant WebExtension API changes?

**Comment by Sancus** [comment]
> 
> 
> Thanks for your help. Do you want me to ping you, when we have backported relevant WebExtension API changes?

Sure, probably a good idea!
