### ISSUE TITLE
A "prohibited symbol" icon is shown next to the supported app version info for every addon

### ISSUE THREAD

**Issue by justdave** [thundernest/addons-server#162]
### Describe the problem and steps to reproduce it:

1. View any addon
1. A screenshot says many words:
<img width="337" alt="Screen Shot 2021-03-26 at 11 27 41 PM" src="https://user-images.githubusercontent.com/307334/112708839-e0053200-8e8a-11eb-81aa-e35e06ffcb96.png">

### What happened?
I believe this is because of the version checking code (designed to work with Firefox and assuming you're using Firefox to view it) so it's saying "this version doesn't work with your version of the app".  Except when you're viewing it in Firefox, it's got no way to know what version of Thunderbird you have, so whatever you have is the wrong version and the icon is displayed.

### What did you expect to happen?
Since we can't auto-detect the Thunderbird version, this just should never display at all. Unless the User-Agent is actually Thunderbird (in case browsing it inside Thunderbird, if we even allow that)

### Anything else we should know?
#30 may be related. If we could tell ATN what version of Thunderbird we're using then it could use that setting to determine the compatibility icon.

**Comment by Sancus** [comment]
I'm not sure I agree that this is a bug. These add-ons shouldn't be installed in Thunderbird. The button that displays IN Thunderbird(which is where you are supposed to be downloading/installing add-ons, as an end-user) is quite different:

![image](https://user-images.githubusercontent.com/479671/112711869-eeeae500-8e88-11eb-9683-68615ddd20fe.png)

You are really not encouraged to use the website in Firefox unless you are a developer, as the install process of downloading an XPI and opening it in Thunderbird is absolute garbage.

**Comment by Sancus** [comment]
@thomasd8 and @jobisoft  brought this up again and I agree it's not ideal but the arguments in the [above comment](https://github.com/thundernest/addons-server/issues/162#issuecomment-808667200) still apply.

That said, I looked into just removing the prohibited icon and it sucks. The whole download button section is shared across the site and the warning section is also used when you are viewing the site in Thunderbird, where it's important to show incompatibility properly.

There's probably a hacky way to do this by modifying the [button JS here](https://github.com/thundernest/addons-server/blob/master/static/js/zamboni/buttons.js#L220), and using z.appMatchesUserAgent and a new CSS class to remove the icon without removing the rest of the section, but I don't have time to dig into this further right now.

Patches welcome but note following constraints:
- No string changes, we can't re-localize them.
- This can't break the prohibited icon/warning section when viewed from inside Thunderbird, as that is the primary install workflow.

**Comment by jobisoft** [comment]
To me it looks like we can tackle that purely by CSS:

1. we need an `isThunderbird` attribute on the body of the generated page, which states if we are in TB or not. That attribute can be used in CSS as part of selectors `[isThunderbird=true]`. Instead, we can also use a more general platform attribute like `[platform=Thunderbird]`. Something like that.

2. https://github.com/thundernest/addons-server/blob/master/static/js/zamboni/buttons.js#L195 needs a span wrapper to be able to hide it (I do not want to change any logic and actually move the addition of | somewhere else)

3. The following span:
```
<span class="download-anyway " style="display: inline;"><a href="/thunderbird/downloads/latest/smarttemplate4/type:attachment/addon-324497-latest.xpi?src=hp-dl-featured" download="">Trotzdem herunterladen</a></span>
```
Needs to not include the `display:inline` style, but a class, so it can obey the body attribute CSS selector (inline css is overruling everything else, and is bad anyway). I have not found that in the source yet.

3. https://addons.thunderbird.net/static/css/restyle/css-min.css?build=8465b02 has this in line 3396:

```
.extra .button.not-available {
 background:#fbfbfb url(../../img/impala/no.png?f10b6fb) 6px 50% no-repeat;
 border:1px solid #b1b1b1;
 border-radius:3px;
 box-shadow:0 2px 0 0 rgba(0,0,0,.1),inset 0 -2px 0 0 rgba(30,30,30,.25);
 color:#b1b1b1;
 cursor:default;
 font-size:14px;
 padding-left:20px;
 padding-right:5px;
 pointer-events:all;
 margin-bottom:5px;
 white-space:normal;
 text-shadow:none
}
```

and the background must be used only, if we are not in TB.

**Comment by Sancus** [comment]
Fixed by https://github.com/thundernest/addons-server/commit/bdd54a133dedc1d9d941a99fd86bcfbbddf41b18 and deployed today.
