### ISSUE TITLE
Uploading add-ons for Beta version (88)

### ISSUE THREAD

**Issue by thestonehead** [thundernest/addons-server#163]
### Describe the problem and steps to reproduce it:
I developed an add-on using Experiments and APIs developed in the Beta version (88) of Thunderbird.
When I upload it to Developer Hub, it says 

> Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?

While my manifest has:
`"applications": {
        "gecko": {
            "id": "the_stonehead@hotmail.com",
            "strict_min_version": "88.0"
        }
    },`

When looking at detailed report, it tells me that some APIs haven't been implemented yet and that some permissions used don't exist.

### What happened?
It rejected my add-on.

### What did you expect to happen?
To accept my add-on.

When will add-ons for beta version be supported if ever? What is the recommended way forward for me?

**Comment by Sancus** [comment]
The only issue here is 88.0 was missing from supported versions, everything else is normal. It should accept your add-on now.

**Comment by thestonehead** [comment]
It does! Thanks.
