### ISSUE TITLE
Cannot upload add-ons - validator fails to return

### ISSUE THREAD

**Issue by Standard8** [thundernest/addons-server#165]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

This happens on both the upload page and the [validator page](https://addons.thunderbird.net/en-GB/developers/addon/validate)

I tried to upload a new version of conversations, and also an older version (3.1.7).  I also tested the nightly version and the release version of Firefox.

### What happened?

The upload proceeds and the progress bar gets to 100%, but then never completes.

### What did you expect to happen?

The validation should complete and I should be able to upload the add-on.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
Fixed this a few hours ago.
