### ISSUE TITLE
The certificate for addons.thunderbird.net expired on 8/9/2021.

### ISSUE THREAD

**Issue by dillenger** [thundernest/addons-server#169]
The certificate for addons.thunderbird.net expired on 8/9/2021.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by shneeba** [comment]
This doesn't just effect addons.thunderbird.net, this is site wide to thunderbird.net

**Comment by dillenger** [comment]
And it's fixed, thanks,
