### ISSUE TITLE
Address Book selection drop down menu has invisible text with Blue Ocean Gradient theme for Thunderbird

### ISSUE THREAD

**Issue by cccoll** [thundernest/addons-server#174]
### Describe the problem and steps to reproduce it:
Thunderbird v 91.2.1 using Blue Ocean Gradient theme by Antonio Souza - Click on Write menu icon to open compose message window.  With multiple address books, click on the address book drop down arrow to select the desired address book.
(Please include as many details as possible.)

### What happened?
Address Book selection drop down opens with black background and black text.

### What did you expect to happen?
Black background and white text

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
All other drop downs and right click menus are fine, and the theme works fine in this version of t-bird other than this issue.

**Comment by Sancus** [comment]
This is an issue with the theme, not the website, contact the author.
