### ISSUE TITLE
Latest version of TB (= 91.6.1) does not allow saving of emails via Move To or via S in Nostalgy++ V3.1.3 to folder which have a '+' in their name

### ISSUE THREAD

**Issue by RichardJones999** [thundernest/addons-server#179]
Two related problems in latest version of TB (= 91.6.1):
(1) Cannot move/save emails via R-click Move - No list of folders.
(2) In Nostalgy++, a recipient folder can be selected but the save function ('S') doesn't move the email if, but only if, there is a '+' in the selected folder's name.

The problem disappears if
(i) Run TB in Troubleshoot Mode (Nostalgy++ and other Add-ons disabled), - i.e., folders now show when select Move.
(ii) Change '+' to '&' in folder names.

Also note: Having turned Add-ons back ON, the R-click Move To, as before, doesn't work (i.e., no folders) but it does work if select Move To in the Message pull-down menu!

So a problem with Nostalgy++ in its functioning with the latest version of TB.

This aside, I must say that Nostalgy++ is an amazingly valuable/time-saving add-on to TB and I am disabled without it.

**Comment by Sancus** [comment]
Not a website bug. Try https://bugzilla.mozilla.org --- but for 2 we don't provide support for add-ons, you want the add-on author.
