### ISSUE TITLE
Croatian locale for ATN missing https://addons.thunderbird.net/hr/thunderbird/

### ISSUE THREAD

**Issue by ovari** [thundernest/addons-server#18]
https://addons.thunderbird.net/hr/thunderbird/ currently always redirects to another language. There should be a Croatian language for add-ons.

**Comment by Sancus** [comment]
No, this isn't supported by AMO because the strings aren't translated: https://pontoon.mozilla.org/hr/amo/

No point in enabling a locale on if 2/3 of the strings aren't translated.
