### ISSUE TITLE
"Invalid version range" indication for all min versions higher as 99 and loss of version text information

### ISSUE THREAD

**Issue by ThunderbirdMailDE** [thundernest/addons-server#184]
### Describe the problem and steps to reproduce it:
Edit addon status and version information. Try to set min version higher than 99.0 and set max version to * (star). Type in the text input field some text. Save the version information. Than come back to this version information.

### What happened?
Invalid version range is indicated and all typed / edited version informations in the **text** input field is lost after saving.

### What did you expect to happen?
Accept the version range and succesfully save the edited version information text instead of silently loose it.

### Anything else we should know?
https://addons.thunderbird.net/en-US/developers/addon/quotecolors/versions/2477405

**Comment by ThunderbirdMailDE** [comment]
Due to some the response of other people, I have to clarify:

The described issue has 2 parts:
- The version range is wrongly indicated as invalid, but saved anyway.
- The typed in **text** in the text input field is lost after saving.

Since the release of Thunderbird 102 is imminent and relevant version numbers are affected, it would be nice if this problem could be fixed.

**Comment by ThunderbirdMailDE** [comment]
Maybe the problem is technically related to the reason, why the * (star) is sorted in between the other version numbers?

![image](https://user-images.githubusercontent.com/47142502/169652613-4dc534a5-5d2e-492a-9df4-a07a9f7f57d8.png)

**Comment by Sancus** [comment]
It's because the version compare code has some problems with 3 digit version numbers. I may be able to fix this next week, should be some hack that I can do. All that code was completely rewritten upstream, so unfortunately it's not really practical to backport their fix.

**Comment by ThunderbirdMailDE** [comment]
Is this fix live? When I try to reconfigure my addon in "Status and Versions" with min version 102.0a1 and increase the max version from 102.* up to "*" (Star), there is still the "invalid version range" error and it is not saved.

**Comment by ThunderbirdMailDE** [comment]
Okay, doesn't appear to be live yet:
https://github.com/thundernest/addons-server/blob/master/src/olympia/versions/compare.py

**Comment by Sancus** [comment]
Fix for this is live now.
