### ISSUE TITLE
Replace usage of InstallTrigger by navigator.mozAddonManager.createInstall()

### ISSUE THREAD

**Issue by jobisoft** [thundernest/addons-server#187]
InstallTrigger has been deprecated. Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1773762 whitelisted ATN to be able to use 
navigator.mozAddonManager.createInstall() instead.

**Comment by MelissaAutumn** [comment]
I meant to post this earlier, but I'll probably need to make another bugzilla ticket for AddonManager.jsm, as `WEBAPI_INSTALL_HOSTS` only includes AMO, not ATN.
