### ISSUE TITLE
Incorrect coding for e-mail addresses, especially with a + (plus sign)

### ISSUE THREAD

**Issue by bjherbison** [thundernest/addons-server#190]
### Describe the problem and steps to reproduce it:
1) Visit https://addons.thunderbird.net/en-US/thunderbird/addon/folder-pane-view-switcher/ .
2) Hover over the Support E-mail link.
3) Click the Support E-mail link.

### What happened?
1) The page loaded! (OK, not really very interesting.)
2) The e-mail link shows as mailto:jik+fpvs@kamens.us .
3) The e-mail is composed to "jik fpvs"@kamens.us ,

### What did you expect to happen?
3) The e-mail is composed to jik+fpvs@kamens.us .

### Anything else we should know?
E-mail sent to jik fpvs"@kamens.us bounced quickly. E-mail sent to jik+fpvs@kamens.us hasn't generated a response but didn't bounce quickly.

Using Firefox Nightly and Thunderbird 91.11 on Ubuntu using XFCE.

**Comment by Sancus** [comment]
Can't reproduce this on Firefox 103.0b9 and Thunderbird 102.0.2, and the mailto link looks totally fine to me:
`<a href="mailto:jik+fpvs@kamens.us" class="email">Support E-mail</a>`

**Comment by bjherbison** [comment]
That's exactly what I see when I inspect the web page. When I click the link Thunderbird creates a new e-mail message with a To field containing this string: "jik fpvs"@kamens.us

When I edit the page to contain
<a class="email" href="mailto:jik%2bfpvs@kamens.us">Support E-mail</a>
the hover over the link appears the same but clicking the link results in a To field with this string: jik+fpvs@kamens.us

I tried with a clean profile for Firefox Nightly and got the same results.

It's possible that something changed between Thunderbird 91 and 102, but Ubuntu hasn't pushed 102 yet.

**Comment by bjherbison** [comment]
The issue is likely in Ubuntu, not Thunderbird.

When I set the Firefox Nightly mailto handler to "Use Mail Reader (default)" (which goes to Thunderbird) the problem occurs. When I set the handler to "Use Thunderbird Mail" the problem goes away.
