### ISSUE TITLE
TB 102 Subject column wastes space

### ISSUE THREAD

**Issue by krem** [thundernest/addons-server#196]
### Describe the problem and steps to reproduce it:
In TB 102 in some folders (new ones), Subject column have too much of padding - so for laptops it wastes space 
### What happened?
![tb102-new](https://user-images.githubusercontent.com/998597/192282122-d9ee5b90-66b5-4741-b0dc-7043d0abae78.png)
### What did you expect to happen?
![tb102-ok](https://user-images.githubusercontent.com/998597/192282168-bd9e9256-af11-4f10-9ebc-6c8ef62aef73.png)

**Comment by Sancus** [comment]
This repository is for website bugs on addons.thunderbird.net -- not Thunderbird issues. Thunderbird bugs [should be filed on Bugzilla](https://bugzilla.mozilla.org/home).
