### ISSUE TITLE
Allow HTML Temp AddOn shows old version

### ISSUE THREAD

**Issue by Alpengreis** [thundernest/addons-server#197]
The HTML Temp AddOn shows the old version v7.0.6 for older Thunderbirds v91.0 - 100.0 on main page https://addons.thunderbird.net/de/thunderbird/addon/allow-html-temp/

It should be the newest v8.1.2 for newer Thunderbirds v100.0 - 107.0 (current release of Thunderbird is v102.3.1) as on versions page https://addons.thunderbird.net/de/thunderbird/addon/allow-html-temp/versions/

PS: The AddOn developer said that he has no influence related to which release version of the AddOn is displayed.

**Comment by Sancus** [comment]
This is intended. If you view the website in Thunderbird, it will show the correct version. The website has no way to know what version of Thunderbird you are using, so it has a default, and that default is still 91.

This will be changed pretty soon now that 102 updates are going out quickly.

**Comment by Alpengreis** [comment]
Oooook, thank you for clarification.

**Comment by wsmwk** [comment]
@Sancus clarified, but the change is yet to be made. However we don't need to reopen because some just created a new issue 199
