### ISSUE TITLE
ImportExportTools NG

### ISSUE THREAD

**Issue by lvsunz3748** [thundernest/addons-server#200]
App did no backup Thunderbird emails today- first time this has happened. App has been backing up as scheduled until tonight. No changes to system since last night.  
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
This is for website issues, please report issues with add-ons to the developer of that add-on: https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/
