### ISSUE TITLE
Unable to upload a valid add on due to validation errors

### ISSUE THREAD

**Issue by Microtribute** [thundernest/addons-server#205]
### Describe the problem and steps to reproduce it:
Upload the following add on,
https://github.com/Microtribute/unify-everything-thunderbird

### What happened?
When it's added directly to Thunderbird as a local package, it gets added and works all right with no issues. However, when I try to publish it on the Thunderbird addon store (https://addons.thunderbird.net/) I am getting the following validation issues.
![image](https://user-images.githubusercontent.com/46481195/203786858-53cf3a64-46aa-451d-b332-6bd96747d8da.png)

The full validation report shows everything is okay though.
![image](https://user-images.githubusercontent.com/46481195/203786890-9f3bcab9-402a-474d-94a2-75f00b2ebbd0.png)

### What did you expect to happen?
It should report no validation issues and enable the `Continue` button for me to be able to proceed to the next step.

### Anything else we should know?
The add on has absolutely no issues.

**Comment by Sancus** [comment]
We hadn't added support for `102.5.0` yet on the website. Your addon has 102.5.0 as both min and max version, that means it will instantly become incompatible as soon as we release any other minor version. I would instead use 102.* as max version.
