### ISSUE TITLE
Error uploading add-on (dictionary): "/version" should match format "versionString"

### ISSUE THREAD

**Issue by flodolo** [thundernest/addons-server#210]
Trying to upload a new add-on (that is already published on AMO), I get this error `"/version" should match format "versionString"`, and I have no clue what it means.

If I open the details page, I also get a `Your JSON file could not be parsed.`.

```
{
    "dictionaries": {
        "en-US": "dictionaries/en-US.dic"
    },
    "version": "110.20230105",
    "browser_specific_settings": {
        "gecko": {
            "id": "en-US-mozilla@dictionaries.addons.mozilla.org"
        }
    },
    "name": "English (US) Dictionary",
    "manifest_version": 2
}
```

I can't find `versionString` here: https://developer.thunderbird.net/add-ons/mailextensions/supported-manifest-keys

The manifest.json in question is also [available here](https://github.com/flodolo/dictionary-en-us/blob/main/extension/manifest.json), the [XPI here](https://github.com/flodolo/dictionary-en-us/blob/main/dictionary.xpi).

**Comment by Sancus** [comment]
I think this means that `110.20230105` is not a valid version string. I think addons-linter fairly recently changed this to be more permissive, so if we update it might fix this. Not sure though.

**Comment by flodolo** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version
https://github.com/mozilla/addons-linter/pull/4527

I noticed the addon-linters is over a year old indeed.

**Comment by Sancus** [comment]
Fixed for this is deployed now.
