### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by holle** [thundernest/addons-server#22]
Dear Mozilla Team,

* This is a Thunderbird add-on related validation error.
* This error occurred during the provisioning of an update for an existing add-on:
  * We allow and encourage an upgrade but you cannot reverse this process. Once your users have the WebExtension installed, they will not be able to install a legacy add-on.
  * Since this is a TB 60 hybird add-on I think the strict validation is too strict in this case.
* My add-on is currently listed (1.0.0.0)
* Submission URL: https://addons.thunderbird.net/de/developers/addon/create-jira-issue/versions/submit/
* Submission time approx.: 2018-08-15 13:53:00 UTC+2/CEST/Central European Summer Time/Germany
* I had to include the manifest.json file with the flag "legacy": true in order for Thunderbird 60 to load my (still) legacy add-on. This was suggested here: [Thunderbird/Add-ons Guide 62](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_62)
* The only "real" change apart from i18n cleanup is the handling of the File's Promise returned by the API call that was introduced.
* The add-on was fully functional on my machines.
* I would like to postpone a WebExtension rewrite of this add-on until the API has stabilized.
* I have received numerous requests from users that were already using TB 60.x pre-relases thus I would like to have a release in the offical channel. please.

Please see the attached file (zip containing xpi) here:
[createjiraissue-1.0.0.60.zip](https://github.com/thundernest/addons-server/files/2292772/createjiraissue-1.0.0.60.zip)

I also ran the [addons-linter](https://github.com/mozilla/addons-linter) on my add-on and fixed all the errors/warnings raised:

09:07 $ addons-linter createjiraissue.xpi
Validation Summary:

errors          0
notices         0
warnings        0

But uploading to https://addons.thunderbird.net/de/developers/addon/create-jira-issue/versions/submit/ still fails with the same error message.

Thanks in advance,
cheers, Holger

**Comment by kewisch** [comment]
Hi Holger, the hybrid WebExtension with legacy: true is not yet supported in Thunderbird 60. Given there is also a Platform limitation that an addon cannot downgrade to a legacy extension I don't believe we should be allowing this on ATN.

Can you check the addons in 57 guide? This should tell you what is required for Thunderbird 60 as well.

**Comment by holle** [comment]
Hi @kewisch ,

I was able to fix the loading problem.
Thanks again for your help :-)

Cheers,
Holger
