### ISSUE TITLE
"Expression Search / GMailUI" is running since hours

### ISSUE THREAD

**Issue by ajfre** [thundernest/addons-server#220]
### Describe the problem and steps to reproduce it:
Search expression: Attachment Name/Type ends with .sh

### What happened?
The search is very, very slow. Is running now for 2 hours on a quite large mail folder tree with approximately 50.000 mails. The progress indicator in the search window is still running.
The standard search needs a few minutes to search a string in the mail bodies.

### What did you expect to happen?
Finish in similar speed as standard search

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
Please report bugs to the add-on author, this repository is for the website.  https://github.com/opto/Expression-Search-NG/issues
