### ISSUE TITLE
Update wording on Permissions modal

### ISSUE THREAD

**Issue by MelissaAutumn** [thundernest/addons-server#222]
Permission string update (https://github.com/thundernest/addons-server/pull/77) now expose a Permissions modal. Which is great! However the wording refers to Firefox, which isn't correct. Easy fix. 

![image](https://user-images.githubusercontent.com/97147377/218225762-3c128d88-7380-42a3-9f9f-87498a8c2cec.png)
Should be in `src/olympia/addons/templates/addons/impala/details.html`

**Comment by Sancus** [comment]
Changing this string will break [the entire paragraph in l10n](https://github.com/thundernest/addons-server/blob/master/locale/fr/LC_MESSAGES/django.po#L577). You can maybe search/replace Firefox/Thunderbird across all the languages as long as nobody's done something weird like translate "Firefox".

**Comment by MelissaAutumn** [comment]
Hmm, that would probably work. I'm guessing we don't have an upstream translation project for ATN?

**Comment by Sancus** [comment]
> Hmm, that would probably work. I'm guessing we don't have an upstream translation project for ATN?

There's no translation project for ATN in Pontoon, no. There will need to be one for the new front-end.

**Comment by MelissaAutumn** [comment]
Cool, just checking to see if I had to upstream the adjustments. 😄
