### ISSUE TITLE
Support the new Photon Add‑ons frontend

### ISSUE THREAD

**Issue by ExE-Boss** [thundernest/addons-server#23]
Right now, [**AMO** (Addons.Mozilla.Org)](https://addons.mozilla.org) uses a new Photon‑based responsive frontend, whereas [**ATN** (Addons.Thunderbird.Net)](https://addons.thunderbird.net) uses the older Australis‑based desktop‑only frontend.

I’d like it if **ATN** would support the new Photon‑based responsive frontend, as I personally prefer it to the older Australis‑based one.

**Comment by wsmwk** [comment]
My POV unless the work required to do this aligns with some other priority, I doubt this will be a priority given other more serious functional and strategic issues on our plate. But I'm sure sancus will weigh in.

**Comment by Sancus** [comment]
Yeah, there's just no way. addons-server was designed with TB and SM in mind. addons-frontend was not designed for any application to use it other than Firefox, and it's missing many things we would need. We don't have anyone with nodeJS/react experience, and while I am certainly capable of doing the necessary modifications and deployment, it would take me months. There is no good business case for spending so much time changing the look of the addons website right now.

Eventually, we will start work on our own front-end, which makes much more sense than trying to adapt Mozilla's Firefox-specific site. I do want to replace the Addons Manager pages and Discovery Pane with a better looking solution, but the website is a much lower priority, given it has an order of magnitude fewer users and is full of extremely complex admin, reiviewer, and developer functionality that even AMO has not replaced yet.
