### ISSUE TITLE
Can't Send Extension to SeaMonkey

### ISSUE THREAD

**Issue by ramazansancar** [thundernest/addons-server#232]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
- I want to send the add-on package that I have sent to Firefox for SeaMonkey. But I get Thunderbird Mail error :(

### What did you expect to happen?
- Establishing the necessary steps to submit the plugin

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
- https://addons.thunderbird.net/tr/developers/upload/0923e11df7114e8e827fbf402e97e47b
![image](https://user-images.githubusercontent.com/8878055/229424644-f60639c7-a59e-43c4-a57f-730acb515efb.png)
![image](https://user-images.githubusercontent.com/8878055/229424679-0b80423d-adc1-4a15-8e7d-198066d5a582.png)

**Comment by MelissaAutumn** [comment]
Hey there, this is actually working expected but the text appears to be slightly incorrect. A GUID is required for all extensions on addons.thunderbird.net. 

You can find an example of a GUID from our sample-extensions repo:
https://github.com/thundernest/sample-extensions/blob/master/hello-world/manifest.json#L9

In this case you need to add or update your `browser_specific_settings` area, and add an `id`. This id can be a unique UUID or an email like string (so maybe like `netflixviewingactivity@ramazansancar.com.tr`)

Cheers,
Mel

**Comment by ramazansancar** [comment]
> Hey there, this is actually working expected but the text appears to be slightly incorrect. A GUID is required for all extensions on addons.thunderbird.net.
> 
> You can find an example of a GUID from our sample-extensions repo: https://github.com/thundernest/sample-extensions/blob/master/hello-world/manifest.json#L9
> 
> In this case you need to add or update your `browser_specific_settings` area, and add an `id`. This id can be a unique UUID or an email like string (so maybe like `netflixviewingactivity@ramazansancar.com.tr`)
> 
> Cheers, Mel

Thanks for Help :)
