### ISSUE TITLE
Statistics page shows zero users

### ISSUE THREAD

**Issue by MyAddonsDev** [thundernest/addons-server#245]
Since July 4th the statistics page on ATN shows zero users (again). For example:
https://addons.thunderbird.net/thunderbird/addon/mail-merge/statistics/usage/?last=30

**Comment by RealRaven2000** [comment]
Apparently the data went online yesterday again (creating a single data point for 112.13 for some of my Add-ons). Let's hope it stays online...

**Comment by Sancus** [comment]
stats should all be caught up now, sorry about that.
