### ISSUE TITLE
Upgrade dockerfile's node from v14 to v16

### ISSUE THREAD

**Issue by MelissaAutumn** [thundernest/addons-server#253]
Needed if we want to use the latest version of addons-linter. I can't actually build the dockerfiles locally on my apple silicon macbook...so we might want to look at either upgrading the dockerfile so it does (potentially very scary), or have someone with a non-mac do it 😄 

As this is blocking the addons-linter upgrade, this also is a pre-req for https://github.com/thundernest/addons-server/issues/247

**Comment by Sancus** [comment]
Fixed by https://github.com/thundernest/addons-server/commit/185af71ed7636329da35ca7159c8bf36dae21511
