### ISSUE TITLE
thunderbird 52.9.1 gmail problems

### ISSUE THREAD

**Issue by luxter111** [thundernest/addons-server#27]
thunderbird 52.9.1 
with different email accounts give the following error when the inbox folder and any other folder of the Gmail account is clicked, is it Thunderbird
problem or something else.with 5 different email accounts loaded in Thunderbird 52.9.1(two outlook and three Gmail accounts)
it's only the Gmail accounts that this error is produced.in browsers all accounts are working ok.

thunderbird 52.9.1 error
Login Failed
Login to server imap.gmail.com  failed.
Retry    Enter New Password    Cancel

click below

https://drive.google.com/open?id=1ArQLWO6TAfpGtnF0HJFOELdAFpzFEzXF

please help fix this error.
on the lower right corner of windows 7 taskbar thunderbird 52.9.1 gives the following message,
Alert from Account(Email address): please login via the web browser;
https://support.google.com/mail/accounts/answer/78754(Failure)
visiting the above link is not helpful in solving the problem.
what can be done to fix this error?
best wishes.

**Comment by rctgamer3** [comment]
This is not a support forum. This issue tracker is only for technical questions with the addons.thunderbird.net site.

https://support.mozilla.org/products/thunderbird
