### ISSUE TITLE
Addon Validation Error (langpack)

### ISSUE THREAD

**Issue by pasqualm** [thundernest/addons-server#28]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.
Ocurred uploading a new version of the addon, the upload form gives a validation error:
Sorry, we couldn't load your WebExtension.
Error: Validation was unable to complete successfully due to an unexpected error.

Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU

If I validate the addon in https://addons.mozilla.org it validates correctly and I can install the addon correctly in a thunderbird 60 clean install

* Whether your add-on is listed or unlisted.
The addon is listed

* The URL where you submitted the add-on.
https://addons.thunderbird.net/ca/developers/addon/valencian-catalan-languag-9730/versions/submit/

* The approximate time you submitted the add-on, with timezone.
23/08/2018 at 18:35 CEST – Central European Summer Time (Daylight Saving Time)

[thunderbird-60.0.1.ca-valencia.langpack.xpi.20180823-1821.zip](https://github.com/thundernest/addons-server/files/2315393/thunderbird-60.0.1.ca-valencia.langpack.xpi.20180823-1821.zip)

**Comment by Sancus** [comment]
You should be able to upload this now. Note that you will likely need to mark the version compatible with Thunderbird manually after upload, as addons-server does not consider Web Extensions to be compatible with anything other than Firefox by default.

You can do this from the add-on's developer page by clicking "View All" next to the "Upload New Version" button in the top left, clicking on the version, and then "Add Another Application" under Compatibility on the version page.

![image](https://user-images.githubusercontent.com/479671/45727065-e65a1b00-bb76-11e8-88b3-714ea7bd6916.png)
