### ISSUE TITLE
Discovery Pane "learn more" link doesn't work.

### ISSUE THREAD

**Issue by Sancus** [thundernest/addons-server#31]
This opens a video on the SeaMonkey page, but it doesn't do anything on the Thunderbird version. The video is pretty useless though, so this should probably either be removed or link to something on the Support site.

See also: [Bug 1481089](https://bugzilla.mozilla.org/show_bug.cgi?id=1481089).

**Comment by wsmwk** [comment]
@Sancus What is the direct URL to the video?

**Comment by Sancus** [comment]
Removed in https://github.com/thundernest/addons-server/commit/c01d676ba0dd750522f2824f2ef2e8e262f1cac8
