### ISSUE TITLE
Dark theme download page does not exists

### ISSUE THREAD

**Issue by RobeDesign** [thundernest/addons-server#34]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Dark theme download page does not exists.

### What happened?
Download not works from the "add to thunderbird" button in "https://addons.thunderbird.net/en-US/thunderbird/addon/macos-sierra-dark/" responding "We're sorry, but we can't find what you're looking for."

### What did you expect to happen?

Theme download

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
Most themes(lightweight themes) cannot be downloaded, they must be installed from within Thunderbird. This currently requires Thunderbird 60.

See: https://github.com/thundernest/addons-server/issues/19#issuecomment-411897770
