### ISSUE TITLE
Add-on validation error

### ISSUE THREAD

**Issue by rjhansen** [thundernest/addons-server#35]
### Describe the problem and steps to reproduce it:
When submitting an updated version of an add-on via [the Thunderbird add-on system](https://addons.thunderbird.net/en-US/developers/addon/misp-ses/versions/submit/) I get told there's been an unexpected error.  The error message is unhelpful and it gives a link to file a bug report in Firefox's system, not Thunderbird's.

### What happened?
The XPI was rejected with no helpful explanation, and I was told to file a bug report in the wrong place.

### What did you expect to happen?
XPI acceptance.

### Anything else we should know?
The attached ZIP file is actually the XPI of the code in question.

[ses_tb-v1.0.zip](https://github.com/thundernest/addons-server/files/2380885/ses_tb-v1.0.zip)

**Comment by Sancus** [comment]
You can try again. I fixed the error with web extensions, but not 100% sure this is going to work as expected, I don't know if addons-server supports legacy extensions with a manifest.json to begin with.

**Comment by Sancus** [comment]
Looks like your addon uploaded and approved OK. You will need to manually mark it compatible with Thunderbird, see: https://github.com/thundernest/addons-server/issues/28#issuecomment-422623903

We're still discussing how to handle web extension compatibility.
