### ISSUE TITLE
Impossible to install theme

### ISSUE THREAD

**Issue by CelestialBird** [thundernest/addons-server#36]
I can`t install any theme to Seamonkey for a long time. Please, help.

![- seamonkey](https://user-images.githubusercontent.com/43334902/45612369-71e68580-ba6b-11e8-9ccb-693ecaaf6b1e.jpg)

**Comment by Sancus** [comment]
It looks like you may be using the AMO Browsing extension, https://addons.thunderbird.net/en-US/seamonkey/addon/amo-browsing-for-seamonkey/

Make sure you are updated to the newest version. If you are, and it still doesn't work, try just going to the theme without using the extension. Lightweight themes should install directly when you click the "Add to SeaMonkey" button, if it goes to https://addons.thunderbird.net/en-US/admin/addon/manage/10900/ it means that the theme isn't even being recognized at all.

**Comment by CelestialBird** [comment]
Thank You!
