### ISSUE TITLE
Cloudflare breaks addon store functionality in torified Thunderbird - Please whitelist Tor in CF for addons.thunderbird.net

### ISSUE THREAD

**Issue by mfc** [thundernest/addons-server#37]
### Describe the problem and steps to reproduce it:

While proxying Thunderbird through the Tor network, accessing any addons.thunderbird.net services in Thunderbird hits a CloudFlare CAPTCHA that cannot be solved. This prevents the updating of existing addons, browing of new addons, etc.

### What did you expect to happen?

User should be able to keep addons up-to-date, download + install new addons, etc from Thunderbird addon store even if they are connecting via a known Tor exit node. They should not have to fill in a CAPTCHA, as it only appears during Addon store browsing and not when one is asking Thunderbird to update existing addons, leading to update failure without a clear user understanding of why it failed.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Pages/services that need to whitelist Tor include:
services.addons.thunderbird.net
addons.thunderbird.net

This is how you whitelist Tor exits in CloudFlare:
https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

**Comment by Sancus** [comment]
Huh, I had no idea this was a thing. I've whitelisted Tor for all of our websites, thanks for reporting. Let me know if you continue to encounter any issues.
