### ISSUE TITLE
Thunderbird Add Theme links broken

### ISSUE THREAD

**Issue by adrienne77** [thundernest/addons-server#38]
### Describe the problem and steps to reproduce it:
All of the "Add Theme" links on the Thunderbird website (https://addons.thunderbird.net/en-US/thunderbird/themes/) are broken. Every time I click on the "Add Theme", the website redirects to the "We're sorry, but we can't find what you're looking for" page.
### What happened?
Went to download a new theme for Thunderbird, cannot find a single "Add Theme" link that works.
### What did you expect to happen?
The theme to download, especially for the recently added themes.

**Comment by Sancus** [comment]
You can't download themes, they have to be installed from within Thunderbird.

See: https://github.com/thundernest/addons-server/issues/19#issuecomment-411897770
