### ISSUE TITLE
Unable to download (any?) theme

### ISSUE THREAD

**Issue by rhoekstra** [thundernest/addons-server#42]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I went to the add-ons site via 1) the web site and 2) the extensions tab in thunderbird. I was looking for a dark theme (to match the new MacOS dark theme :).

But I tried multiple (also non-dark) themes, and all brought me to a 404 not found page when i clicked on the '+ add to Thunderbird' button.

### What happened?
I got a 'We're sorry, but we can't find what you're looking for' page, instead of the plugin/theme being downloaded.

### What did you expect to happen?
That the plugin/theme would be loaded.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
Not sure what other details could be of help, other than:
OS: MacOS High Sierra
Thunderbird Version: 52.9.1 (64-bit)
Browser: Chrome 69

**Comment by Sancus** [comment]
Most themes cannot be downloaded, they must be installed within Thunderbird. See: https://support.mozilla.org/en-US/kb/install-themes-change-look-thunderbird

Note that this requires Thunderbird 60, which can be downloaded from https://www.thunderbird.net -- there are a number of problems with TB52 and the addons site at this point.
