### ISSUE TITLE
Cannot upload WebExtension with WebExperiment

### ISSUE THREAD

**Issue by benbucksch** [thundernest/addons-server#46]
WebExtensions are the new kind of extensions, the only one that Firefox supports.
They are very new for Thunderbird. Thunderbird supports almost no APIs for WebExtensions yet.
Thus, any Thunderbird WebExtension likely has to create new APIs, via the WebExperiments API mechanism. It's essentially chrome code implementing new APIs. Security-wise, that's on the same level as bootstrapped addons.

We developed a WebExtension with 2 WebExperiment APIs. But addons.thunderbird.net refuses the upload.

### Describe the problem and steps to reproduce it:
1. Create a new extension
2. Upload XPI of WebExtension with WebExperiment. [Example XPI](http://www.beonex.com/owl/latest.xpi)

### What happened?
Upload refused
"
Error with latest.xpi
100% complete · 49.91 KB of 49.91 KB
We have enabled a new linter to process your Add-on. Please make sure to report any issues on GitHub
Your add-on failed validation with 1 error.
    You cannot submit this type of add-on
See full validation report
"
The full validation report finds 17 warnings about unknown APIs (the ones we created), but no errors.
"
General Tests
0 errors, 17 warnings, 0 notices
Security Tests
0 errors, 0 warnings, 0 notices
Extension Tests
0 errors, 0 warnings, 0 notices
Localization Tests
0 errors, 0 warnings, 0 notices
Compatibility Tests
0 errors, 0 warnings, 0 notices
"

### What did you expect to happen?
Upload is allowed. Addon reviewers review it in the same way and with the same care as they review bootstrapped addons.

### Anything else we should know?
[Code for AMO addon linter that produces the error](https://github.com/mozilla/addons-linter/)

**Comment by benbucksch** [comment]
The linter only shows warnings. So, it might not be the linter, but the importer itself that throws the error.

**Comment by benbucksch** [comment]
> What's your email on ATN?

Sent by mail to your @thunderbird.net account.

> auto-approval would be very bad

Agreed.

Right now,  I cannot even submit the addon for review. If the upload is allowed (after the patch), I presume that the addon goes into normal review. (Although I don't know how ATN is set up.)

I would expect a normal review like for bootstrapped addons.

**Comment by Sancus** [comment]
I added you to the group so you should be able to submit this. I agree that it would be OK if the addon goes into normal review, the issue is that I think it does not... but I guess we'll see what happens when you submit your addon because now that you're in the group, you should bypass this check as if it was removed.

**Comment by benbucksch** [comment]
Thank you!

I was able to upload and submit now. My addon is listed as "in review". It is not visible on public ATN website, it gives a [no such thing](https://addons.mozilla.org/de/firefox/addon/owl-for-exchange/) (URL as given given by addon admin page).

**Comment by Sancus** [comment]
It went into the auto-approval queue that all web extensions go into, and looks like it's been auto approved, that's what I expected to happen. I do notice that it appears to have the correct compatibility, did you set that manually?

**Comment by benbucksch** [comment]
Andrei Hajdukewycz schrieb am 20.10.2018 um 04:53:
>
> I do notice that it appears to have the correct compatibility, did you 
> set that manually?
>

Yes. ATN offered me only Firefox categories, and also in the metadata of 
the addon seemed to think that it was a Firefox addon. That made me 
suspicious that something went wrong and I tried to manually fix it. 
After all, it's also confusing for end users to see a "Firefox" addon.

Ben

**Comment by benbucksch** [comment]
Andrei Hajdukewycz schrieb am
      20.10.2018 um 04:53:
    
    
      It went into the auto-approval queue that all web extensions go
        into, and looks like it's been auto approved, that's what I
        expected to happen.
    
    
    Ah, now I understand what you meant. The AMO code considers only
    WebExtensions (in contrast to bootstrapped) to be safe and not
    needing review. And the "no web experiments" rule upholds that they
    are safe.
    
    So, we'd need an additional code change that pushes web extensions
    with an experiment into the normal review queue for bootstrapped
    ones. Got it!

**Comment by benbucksch** [comment]
Given that I have the ability to create and submit them, I guess my immediate need is fulfilled. Thanks a lot. I'll keep this open for the general question and for others.

**Comment by Standard8** [comment]
@Sancus Can you look at fixing this asap? With 68 now out, various people are starting to experiment with upgrading to WebExtensions and using WebExtension experiments.

I'm trying to do this with the latest version of my add-on, and someone else has been trying here:

https://thunderbird.topicbox.com/groups/addons/T409cd22eca2f3864/cant-upload-addon-on-addons-thunderbird-net

**Comment by Sancus** [comment]
These are allowed now, and go in the regular review queue.
