### ISSUE TITLE
Need 60.x versions for compat

### ISSUE THREAD

**Issue by benbucksch** [thundernest/addons-server#49]
On the addon version page, I can set the compatibility. But I cannot select Thunderbird version 60.3. Only 60.0, 60.0a1 and 60.0a2 are available. 60.1, 60.2, 60.3, 60.4 etc. are missing.

I need this, because my addon only works with 60.3 or later.

**Comment by benbucksch** [comment]
@Sancus : Could you please add TB 60.x versions (including 60.5, 60.6 etc.) to the list of Thunderbird versions that I can select for compatibility?

* Our extension needs changes that have been landed only in TB 60.3. I've mentioned that, but users don't read it and complain that it doesn't work on TB 60.2. Unfortunately, [Ubuntu still has only TB 60.2](https://packages.ubuntu.com/search?keywords=thunderbird&searchon=names&suite=all&section=all) as newest version.
* I now need to release changes that require TB 60.4. Users with TB 60.3 will be broken, if they update the extension, which will be a problem for our Linux users.
* There are other changes pending that we need which will hopefully land in TB 60.5. We will need to set a hard dependency on that in future versions of our addon.
* I expect that to continue, because we're on the cutting edge with our WebExtension addon, so having all future TB 60.x versions already in the DB would be helpful.

This is urgent for us, to not break users on the release that I'd like to make right now.

**Comment by Sancus** [comment]
Apparently these are manually added, I had no idea. I'll have to write a script to pull them automatically from the release date at some point.

In the mean time, I've added:
```
    60.2.1
    60.3.0
    60.3.1
    60.3.2
    60.3.3
    60.4.0
```
Which are all of the official stability releases we've made AFAIK.

**Comment by benbucksch** [comment]
Thanks!

**Comment by RealRaven2000** [comment]
Nice one - thanks, I also want to use this for max version so I am forced to update (and deal with compatibility versions) my  Add-ons regularly. just a pity we cannot say maxVer<60.5 as eemergency releeases susch as 60.3.1 are not covered by 60.3 (and I was told 60.3.* as maxver would be madness)
