### ISSUE TITLE
Not a proper error message displayed - sites are down for data copy 

### ISSUE THREAD

**Issue by ioanarusiczki** [thundernest/addons-server#5]
STR:

1. Load AMO dev and switch to the old pages.
2. From Other Applications drop down menu Click on Thunderbird and then on Seamonkey.

Expected results:
A proper message displayed when sites are down for data copy.

Actual results:
503 Service Temporarily Unavailable

Notes:
This issue is reproducible on AMO dev and AMO stage with FF61(Win10).
![service unavailable](https://user-images.githubusercontent.com/33448286/42574298-dbe88408-8526-11e8-918a-3a27770675f7.gif)

**Comment by Sancus** [comment]
Thanks for the report. I'm working on a better error message now, will update this issue when it's in place.

**Comment by Sancus** [comment]
https://addons.thunderbird.net/ now has a proper error message and ETA.
