### ISSUE TITLE
Cannot login to my Firefox account. Internal Server Error 

### ISSUE THREAD

**Issue by alehro** [thundernest/addons-server#52]
Problem:
When I try to login server responds with JSON: {detail : "Internal Server Error"}

Details:
I am developer of an addon for Thunderbird. On Friday I have added secondary email and made it primary. After that I have logged out. Now I cannot login.

This is copy of issue [https://github.com/mozilla/addons/issues/836]( https://github.com/mozilla/addons/issues/836). Guys there told me that Thunderbird addon accounts are separate from Fireforx'. Whom should I email for help?

**Comment by alehro** [comment]
Any response to that? This is not funny. The addon has decent amount of users and they are pretty worried about the state of the art. One of the users volunteered and updated addon to be compatible with current TB version. I was supposed to upload the new version but because of the stupid situation I can't do that. What should I tell him and users?

**Comment by wsmwk** [comment]
@ryanleesipes

**Comment by alehro** [comment]
It is alehro00@gmail.com

**Comment by Sancus** [comment]
Try logging in now.

**Comment by alehro** [comment]
It works. Thank you very much.

**Comment by Sancus** [comment]
You're welcome, closing this.
