### ISSUE TITLE
Cannot change default language

### ISSUE THREAD

**Issue by benbucksch** [thundernest/addons-server#55]
For some reason, the default language for my addon was set to German. I didn't intentionally set this.

Now, I cannot change it anymore.

Reproduction:
1. Go to the  [addon settings page](https://addons.thunderbird.net/developers/addon/owl-for-exchange/edit), to section "Add-on-Details" with a field "Default language"
2. Click "Edit" above that section
3. Change dropdown field "Default language" to "English (US)"
4. Fill out the "Description" and "Homepage" fields. Note that they still say "German"/"Deutsch", which is wrong.
5. Save

Actual result:
* Error (in German): "Before changing your default language, you must have a name, summary, and description in that language. 'description' is still missing."
* The changes are not saved
* "Description" and "Homepage" fields still say "German", even though the "Default language" has been changed to "English".
* I have no way to fix this.

Expected result:
* Once I change the default language, the other 2 fields also change to that language.
* Saving works
* When navigating to my addon page as an end user with a language that the addon has no description translation for, the description is displayed in English, the new default language.

**Comment by benbucksch** [comment]
Affected addon: [Owl](https://addons.thunderbird.net/developers/addon/owl-for-exchange/edit). If this bug can't be fixed quickly, could you maybe fix this in the DB for my addon?

**Comment by Sancus** [comment]
Not a bug, the UI is just mildly confusing. I'm not sure why your add-on got set to German(possibly a default pulled from when you submitted it using the german site locale or accept-language or something?), but:

- Click in the top right to switch to the en-US localization.
![image](https://user-images.githubusercontent.com/479671/49318456-74bf1700-f4ad-11e8-81f4-dc1fbbc1f10b.png)
- Add a description in the "Add-on Details" section and then click Save.
![image](https://user-images.githubusercontent.com/479671/49318463-7ee11580-f4ad-11e8-91f7-aabc60181789.png)
- Now you can switch the default language to en-US.

I did this and the add-on's default language is now en-US.

**Comment by benbucksch** [comment]
Ah, I understand. I was confused, the summary and description are in different sections.
Thanks for fixing it up!
