### ISSUE TITLE
Validation fails: Received an empty response from the server; status: 502

### ISSUE THREAD

**Issue by dillenger** [thundernest/addons-server#56]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
I can't upload a new version for my theme, phoenity_shredder-3.5.55-tb.jar.
Validation fails with one error and a message: 
Received an empty response from the server; status: 502

### What did you expect to happen?
It should work, I can install the theme here, so I don't think anything is wrong with the file

### Anything else we should know?

Attached are a screenshot and the file I tried to upload renamed to *.zip.

(Please include a link to the page, screenshots and any relevant files.)

![image](https://user-images.githubusercontent.com/571067/49629427-bab63680-f9e9-11e8-80d9-81aeb6b2d21c.png)

[phoenity_shredder-3.5.55-tb.zip](https://github.com/thundernest/addons-server/files/2655968/phoenity_shredder-3.5.55-tb.zip)

**Comment by Sancus** [comment]
This should be fixed, thanks for the report.
