### ISSUE TITLE
version notes are not uploaded / updated (or it takes weeks)

### ISSUE THREAD

**Issue by RealRaven2000** [thundernest/addons-server#57]
### Describe the problem and steps to reproduce it:
upload a new version of my ADd-on  (this happens every time)
I usually add version histories as html unsigned list with links to my bugzilla

### What happened?
version notes to not appear for several days
See:
https://addons.thunderbird.net/en-GB/thunderbird/addon/smarttemplate4/versions/?page=1#version-2.0

### What did you expect to happen?
version notes should be uploaded immediately. they are definitely stored in "manage versions"
I also notice that I cannot enter version history *during* uplooad of the add-on I can only edit it aftere it has been submitted for review (this used to be different)

### Anything else we should know?
here is an example release note text:

[st4-release2.0.txt](https://github.com/thundernest/addons-server/files/2712442/st4-release2.0.txt)

**Comment by Sancus** [comment]
I'm not sure what you're reporting here. Your version 2.0 had an empty en-GB localization listed at https://addons.thunderbird.net/en-US/developers/addon/smarttemplate4/versions/2469054 in the top right. Deleting that localization made the en-US notes, which are correct, show up.

There is not any kind of delay with version notes, they're just stored in the database for each language. If your language has a localization that is empty, you won't see any notes.

**Comment by RealRaven2000** [comment]
thanks - I will see if it works the next time. It obviously made the version notes field disappear on the upload version stream, it wasn't obvious to me that this was caused by an empty translation. The addon does not contain an en-GB locale but I am located in Ireland. maybe that's what caused it to appear. I am pretty sure I had the samee problem with QuickFolders, so I am going to check there wheteher an empty En-gb locale has been createed. It may be from the migration from AMO.

**Comment by Sancus** [comment]
Feel free to reopen if you have steps to reproduce, it's entirely possible that something in the upload process is creating empty localizations, but it's hard to fix without knowing what or if it's repeatable.

**Comment by RealRaven2000** [comment]
I don't know how to reopen, but I can definitely reproduce it. I uploaded a new version for quickFilters yesterday, and noticed my page always reads "en-GB" once I go to
https://addons.thunderbird.net/
it auto-redireects me to the GreatBritain domain:
https://addons.thunderbird.net/en-GB/thunderbird/
which then produces the behavior (no version notes field visible) - the actual Add-ons never have a en-GB localisation, I think it is the server that decides to bring me to the en-GB version because of my location (Ireland)
By editing the URL, changing en-GB part to en-US I was able to enter the version notes without a hitch.

**Comment by Sancus** [comment]
Um yes, but the problem is that they DO have an en-GB localization and that it's empty. That's the cause. The question is where that empty localization is coming from.

![image](https://user-images.githubusercontent.com/479671/50575415-fc04f080-0db3-11e9-84ac-45f28abcf0b0.png)

**Comment by mschoettle** [comment]
I just ran into this exact problem. My add-on (Toggle Headers) itself contains two localizations (`en` and `de`) but I only enter English descriptions on the add-on page. 

Is it possible that this is the problem? I suspect that it automatically adds all locales of the add-on. But even then, it would be better, IMHO, to fallback to the default if no description was provided for additional locales.
