### ISSUE TITLE
Featured add-on doesn't show up in featured list

### ISSUE THREAD

**Issue by oeekker** [thundernest/addons-server#61]
### Describe the problem and steps to reproduce it:
I was looking at Thunderbird's featured add-ons and noticed that my add-on Mail Redirect wasn't listed:
https://addons.thunderbird.net/en-US/thunderbird/extensions/?sort=featured
When you got to the page for my add-on though, it is clearly marked as featured:
https://addons.thunderbird.net/en-US/thunderbird/addon/mailredirect/

### What happened?
Add-on Mail Redirect doesn't show when viewing all featured add-ons.

### What did you expect to happen?
Add-on Mail Redirect should show up in the list.

### Anything else we should know?
Just the other day, my whole add-on went missing on ATN after uploading a new version. It appeared that my add-on has a manifest.json and ATN "thought" it was a Firefox webextension, so I had to add the applications Thunderbird and SeaMonkey manually in de developer hub.

**Comment by Sancus** [comment]
https://addons.thunderbird.net/en-US/thunderbird/extensions/?sort=featured

Seems to show now.
