### ISSUE TITLE
ATN footer talks about Firefox

### ISSUE THREAD

**Issue by benbucksch** [thundernest/addons-server#68]
The footer (both in blue and in white) talks about Firefox. It should talk about Thunderbird, and link to Thunderbird resources. Including the documentation for Thunderbird MailExtension APIs.

**Comment by benbucksch** [comment]
CC @darktrojan

**Comment by Sancus** [comment]
These were removed in https://github.com/thundernest/addons-server/commit/fb5933a51deed655645f875b6c87fbab516f21f4 .
