### ISSUE TITLE
All add-ons containing a manifest.json are considered WebExtensions

### ISSUE THREAD

**Issue by oeekker** [thundernest/addons-server#69]
I submitted my add-on Mail Redirect and it was automatically accepted and didn't need manual reviewing, because it contained a manifest.json.

The manifest.json file however, did contain a "legacy" property, indicating that the add-on was in fact a legacy add-on that uses Thunderbird's overlay loader to load the XUL/JavaScript.

This type of add-on shouldn't get automatically accepted, but stay in the review queue.

**Comment by Sancus** [comment]
Legacy add-ons using manifest.json are a weird Thunderbird hack so yeah, addons-server was never designed for these.

I don't know how easy it is to change this but I'll look into it eventually. If @darktrojan knows where to change this or how difficult it is I'd welcome a patch.

**Comment by darktrojan** [comment]
Sorry, I missed this. It *should* be reasonably easy to fix.

**Comment by oeekker** [comment]
@darktrojan could you please look into this again, if it /should/ be reasonably easy to fix? last week another add-on was automatically accepted, while it should have been reviewed.
