### ISSUE TITLE
Can't upload an update for a theme

### ISSUE THREAD

**Issue by dillenger** [thundernest/addons-server#7]
### Describe the problem and steps to reproduce it:
Currently I can't upload an update for a theme, Phoenity Shredder.
### What happened?
After uploading the page gets stuck at "Validating phoenity_shredder-3.5.47-tb.jar"
### What did you expect to happen?
The validation process should finish.
### Anything else we should know?
https://addons.thunderbird.net/en-US/developers/addon/phoenity-shredder/versions/submit/
Using 64-bit Firefox 61.01 on Linux, no interfering extensions AFAICS, this used to work on AMO.

**Comment by Sancus** [comment]
Hmm, that's quite strange. I can't reproduce the error with existing versions of the theme, they seem to upload just fine.

Can you link the file or email it to sancus@thunderbird.net ? Thanks.

**Comment by Sancus** [comment]
There were two problems here:
1. The AES_KEYS setting for api key generation was misconfigured, it requires a very specific dictionary format to work that I wasn't aware of. This was causing a number of exceptions on any operation related to API keys.

2. The validator checks to see if you put your API key in the addon somewhere(I think to warn you if you did), and it was trying to look up API keys. The database snapshot from AMO has all the API key fields mangled for security reasons, but they were not treated as revoked. Thus the site was trying to read data, and this was causing another exception. Revoking all keys fixed this.

P.S. In your email you mentioned stats, it's known that they are not working, and it may be some time before they are. See: https://discourse.mozilla.org/t/new-site-for-thunderbird-add-ons/30027/4

Thanks for your report.
