### ISSUE TITLE
Can I delete stale TB-only extensions on AMO?

### ISSUE THREAD

**Issue by dillenger** [thundernest/addons-server#70]
After the transition from AMO to ATN I have some stale TB-only extensions left on AMO.
Can I now delete these without risk for the versions on ATN?

For example:

https://addons.thunderbird.net/en-US/developers/addon/phoenity-shredder/versions
https://addons.mozilla.org/en-US/developers/addon/phoenity-shredder/versions

**Comment by Sancus** [comment]
Yeah, there's no sync between AMO and ATN database. There was a one-time transfer in July and now the ATN database and site are completely independent, and Thunderbird only uses ATN.

So anything you do on AMO has no effect on ATN.
