### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by siefkenj** [thundernest/addons-server#71]
[mailmergep@example.net-1.0.0.zip](https://github.com/mozilla/addons/files/2858664/mailmergep%40example.net-1.0.0.zip)

This is a new addon submitted Feb 13, 2019 at 3:15GMT
The validation report is at https://addons.thunderbird.net/en-US/developers/upload/a31623cb41114d688641345fdb359631

I believe the error occurred because of too many warnings produced by the automated review. The addon has a component compiled with wepback and react. The full source can be found at
https://github.com/siefkenj/MailMerge

**Comment by Sancus** [comment]
I really don't have any idea what I'm supposed to do with this. I don't think it makes any sense to spend time trying to modify the validator to permit hundreds of warnings. The errors themselves have no information.

@kewisch Any ideas?

**Comment by siefkenj** [comment]
Any updates on this? Surely there are other addons built with react. Do they have a way around this issue? Do I have something misconfigured?

**Comment by Sancus** [comment]
So, I'm not sure what version of react you're using, but after investigating a bit I think that to use libraries they need to be in a file with an allowed hash, not just any arbitrary pile of javascript.

You can see what hashes and files are allowed in [amo-validator 1.11.0](https://pypi.org/project/amo-validator/1.11.0/#files) under \validator\testcases\hashes-allowed.txt in the .tar.gz file.

We are not capable of doing new releases of this library right now and it's been deprecated as of the end of January by Mozilla... we'll probably need to figure out if we can take over it or fork it and do our own releases to be able to update this stuff, but that may be a few weeks.

Below are some of the permitted react files from version 1.11.0 which is what we're using right now, 1.11.2 doesn't seem to have added any either:

`504aa7e7eb72cdecc3e80e4704c35395ce665e49adfa88537c204fb5731a19bd react-dom.15.6.1.react-dom.min.js`
`8af74f027e61e94ebbcfa38f8307e22ccf6e83a95ebf199816a58dc4d095d181 react.15.6.1.react.min.js`
```
2cf49421691b9dbf1916f970e1532a724f39c10b36b3becc794114559f6e352b react16.16.0.0.react-dom.development.js
0dcb93a5c7859e1fa909ffe239b591ec329bfea81bf5e059ecb1b6f7e1ca7058 react16.16.0.0.react-dom.production.min.js
493ecfdc30046522c71c19c2f80c913460d115b4872bb1223c2de10639153990 react16.16.0.0.react.development.js
de59b0d4504aa0350c13775fec9b78859f3eda83dea21d60dded98bb7866d54a react16.16.0.0.react.production.min.js
```

**Comment by siefkenj** [comment]
Hmm, interesting. I am using React 16.8, since I need the new _Hooks_ features. I suppose I could load these resources from a CDN in which case they would not be scanned.

All of my large javascript blobs are being run from an `<iframe />` with restricted permissions. Is it likely that in the future such code would be given more relaxed checks?

**Comment by kewisch** [comment]
Remote code excution is not allowed per our policies, iframe or not. For now you'll have to either wait until we update the validator with the newer react links, or find another way to reduce warnings.

**Comment by Sancus** [comment]
Considering amo-validator is deprecated, and supported versions of Thunderbird now use web extensions which use the newer linter, I don't think this is relevant anymore. We're not going to spend dev time updating the validator for legacy add-ons.
