### ISSUE TITLE
Delete/erase/remove account - addons.thunderbird.net

### ISSUE THREAD

**Issue by ldexterldesign** [thundernest/addons-server#74]
Hi,

Hope you're well

I'd like to delete my https://addons.thunderbird.net account

Please provide an email point of contact to action this request?

Look forward to reply

Yours faithfully

NB I've been directed here by Philipp Kewisch at via amo-admins@mozilla.org

**Comment by kewisch** [comment]
Hi Lewis. Let's continue our discussion via email. You can delete your account there as I mentioned.

**Comment by Sancus** [comment]
You can delete your account at the bottom of the account interface at https://addons.thunderbird.net/en-US/thunderbird/users/edit
