### ISSUE TITLE
Approved/Rejected themes don't go away in the updates tab of the theme reviewer tools

### ISSUE THREAD

**Issue by Paenglab** [thundernest/addons-server#76]
In the updates tab of the theme reviwer tools https://addons.thunderbird.net/en-US/reviewers/themes/updates the Rejected/Approved themes are still shown in the list. They should go away when they have this states.

Especially the approved themes show in detail view that they are approved. One of them I tried to approve a second time but it's still in the list.

**Comment by Sancus** [comment]
Not sure what's going on here, if there's an issue with your account permissions or ?

The rejections at least don't seem to be done correctly, you need to click Reject, pick a Reject Reason, and then click "Commit Review".

When I do this, the theme drops off the list. When I do the same for Approve -> Commit, it also drops off the list.

**Comment by Paenglab** [comment]
The rejected themes where always there when I started to review themes.

For the Approve, it can be a permissions issue but I can't say as I have not enough permissions to check ;)

**Comment by Sancus** [comment]
OK, so I looked in the log, and it looks like you've successfully approved other themes and had them clear properly?

After testing I think these old themes that date from months/years before the ATN migration had some database issue, force rejecting them myself seems to have cleared them.

I'm going to close this, but please reopen if you run into a theme that won't approve or reject properly again.
