### ISSUE TITLE
WebExperiments immediately disabled after upload

### ISSUE THREAD

**Issue by benbucksch** [thundernest/addons-server#78]
I am uploading a new version of [Owl](https://addons.thunderbird.net/en-US/thunderbird/addon/owl-for-exchange/). Owl is a WebExtension with WebExperiments.

Previously, I ran into #46. This has been fixed. Until a few weeks ago, I could upload new versions of the addon and they became live almost immediately (within 5 minutes).

However, now, while the upload works fine (i.e. this is not #46), the version gets disabled immediately after upload. On [the versions page](https://addons.thunderbird.net/en-US/developers/addon/owl-for-exchange/versions), I only see "Disabled by Mozilla". There is no explanation at all, and no way for me to re-enable it. Apparently, ATN admins have the ability to re-enable it. But that's obviously not a solution.

![image](https://user-images.githubusercontent.com/1907525/54785411-7102fc00-4c26-11e9-9974-f37f4392f834.png)

**Comment by Sancus** [comment]
The bug was in Ben, not in the site ;)

**Comment by benbucksch** [comment]
Yeah. Ben clicks on big shiny red buttons. And missed the small blue one.

**Comment by benbucksch** [comment]
:man_facepalming:
