### ISSUE TITLE
Clicking "Download for Linux" in Firefox attempts to install add-on in the browser

### ISSUE THREAD

**Issue by RalfJung** [thundernest/addons-server#8]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I went to https://addons.thunderbird.net/en-US/thunderbird/addon/lightning/ and clicked "Download for Linux". This is using Firefox 62 (beta) on Linux (Debian).

### What happened?

Firefox asks whether I want to install the add-on.

### What did you expect to happen?

Firefox should offer to download the add-on (I vaguely remember that to be the case on the old addons.mozilla.org page).

**Comment by MadMattAu** [comment]
My recollection (admittedly under windows) is that because of the XPI extension was used in both, you had to right clci and choose save target as to actually bypass the Firefox eagerness to install addons it had nothing to do with.

**Comment by mkmelin** [comment]
No, you didn't have to manually right click and choose save as. It used to just offer to save for Thunderbird add-ons. I think the site just set Content-Disposition: attachment

**Comment by Sancus** [comment]
This is fixed. Thunderbird add-ons should now properly download instead of triggering for browser installation.
