### ISSUE TITLE
500 error on certain add-ons with TB 67.0b2

### ISSUE THREAD

**Issue by Sancus** [thundernest/addons-server#83]
https://addons.thunderbird.net/en-US/thunderbird/addon/remove-duplicate-messages-alte/ returns a 500 error with TB67, but not via Firefox or TB60.

I suspect an issue with the code to return different versions based on Thunderbird user agent. Not sure why this add-on in particular is an issue though, as other add-ons with no compatible versions are fine.

cc @darktrojan but I will also look at this in the next few days since it's probably hard to reproduce without this specific add-on in your database.

**Comment by darktrojan** [comment]
Is there some deleted/disabled version of it? One with no compatibility info? I guess that could cause problems.

Maybe the code I wrote should have a try…except block in an appropriate place…
