### ISSUE TITLE
cannot update legacy Add-ons after releasing WebExtension version

### ISSUE THREAD

**Issue by RealRaven2000** [thundernest/addons-server#87]
### Describe the problem and steps to reproduce it:
I am trying to upload a bugfix for quickFilters for my ESR users and ATN won't let me now. I had uploaded a Webextension version with the legacy flag, which blocked me from uploading any new versions of the legacy build for my existing TB60 users. I also found out that Tb60 does not support the legacy flag, so effectively this blocks us from support ESR60 and ESR68 with the same Extension - we would be forced to rebrand and publish a completely different Add-on in order to support both user groups.

### What happened?
A validation error:
"You cannot update a WebExtensions add-on with a legacy add-on. Your users would not be able to use your new version because Firefox does not support this type of update."

### What did you expect to happen?
ATN should allow hosting both versions so that my beta users can try out the new version and my existing ESR users (the vast majority) can be provided with updates. It is currently not possible to build a single version that supports both, so my expectation is that I can upload 2 different versions (which are managed via minver / maxver) to serve both groups - obviously with slightly differing version numbers. Also, it seems the "firefox / Webextensions" part of the error somehow probably doesn't really apply to Thunderbird.

### Anything else we should know?
https://i.imgur.com/wGQ2nGf.png
the only workaround, for now, is that I have to delete all the Webextension versions in order to update legacy users, then re-upload the WebExtension. This effectively blocks us from trying out versions for our beta users.

**Comment by RealRaven2000** [comment]
With help from :nONo|DodO  I came up with a "hybrid" installer that includes both install.rdf and manifest.json - it is possible to have strict_min_ver 60 in the manifest - Thunderbird 60 will still prefer parsing the install.rdf instead. I have to test where ATN reads its minimum version in this case - I guess that it will ignore the install.rdf once a manifest file is included.

the hybrid approach (as long as it won't break in future versions of Thunderbird) seems like it can be used to circumvent the limitation of the Add-on parser.

**Comment by RealRaven2000** [comment]
An additional workaround that is currently possible was discovered by John Bieling: you can still upload *lower* Add-on version numbers for a legacy add-on as long as the last Webextension's version is higher. This will avoid triggering the validation mechanism that doesn't allow for "roll-back" / "downgrade" from wx to legacy. In this way, one could release all wx as 3.* while publishing legacy "underneath" as 2.* in parallel - of course, the use of matching minver / maxver / strict_min_ver needs to be intelligently managed by the Add-on author.

**Comment by Sancus** [comment]
John Bieling's workaround is now the official plan for this.

https://developer.thunderbird.net/add-ons/tb68#uploading-your-updated-add-on-to-atn
