### ISSUE TITLE
Change "addons.mozilla.org" in reviewer email templates to "addons.thunderbird.net"

### ISSUE THREAD

**Issue by Sancus** [thundernest/addons-server#9]
There's a bunch of email templates in `src/olympia/reviewers/templates/reviewers/emails` that have the wrong site URL hard coded, this is an easy fix and should cause very few if any conflicts with future patches, so might as well do it.

**Comment by kewisch** [comment]
bonus points for changing the hardcoded host to a variable and also pushing that patch upstream :)

**Comment by Sancus** [comment]
If they'll take the patch I'll definitely do it that way.

**Comment by Sancus** [comment]
This was fixed a long time ago by https://github.com/thundernest/addons-server/commit/da6fdef9f970bdb81f39b51c5de14381d7494418
