### ISSUE TITLE
Cannot update list entry on addons.thunderbird.net of addon

### ISSUE THREAD

**Issue by jmozmoz** [thundernest/addons-server#97]
### Describe the problem and steps to reproduce it:
I cannot update my list entry ("Basic Information" and "Add-on Details") on the "Edit Information" page of my addon (CompactHeader):
https://addons.thunderbird.net/en-US/developers/addon/compactheader/edit

### What happened?
After pressing "Save Changes" the field is greyed out and the cricle symbol never stops.

### What did you expect to happen?
The list entry should be saved and updated

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by Sancus** [comment]
This works for me, and I have no way to diagnose what is wrong for you.

Maybe try this url, it bypasses the cache layer: https://reviewers.addons.thunderbird.net/en-US/developers/addon/compactheader/edit

**Comment by jmozmoz** [comment]
Ok. For whatever reasons, it works with Chrome but not Firefox. I am using different addons for privacy like uMatrix and uBlock Origin. But should they be deactivated on this website automatically (like on addons.mozilla.org)?

**Comment by Sancus** [comment]
I run uBlock Origin in Firefox and it works fine. I don't know what uMatrix is, If you're using add-ons that block XHRs for some reason that would break that. You should see a successful XHR POST in the web console when you click the "save" button.

![image](https://user-images.githubusercontent.com/479671/60055175-94a86900-9691-11e9-95d4-317c740f9074.png)

Maybe whatever add-on is blocking the request will provide some information in there.

**Comment by jmozmoz** [comment]
I think, I know wat caused the problem:
The firefox preference network.http.sendRefererHeader was set to 0 (no referer) using the addon https://add0n.com/privacy-settings.html). If I enable referers, then saving works. 

Just out of curiosity: The edit POST uses https. Why does this browser setting has an impact?

Otherwise, this issue report can be closed.
