### ISSUE TITLE
Add-ons displayed forTB version filter are incompatible

### ISSUE THREAD

**Issue by dryquart** [thundernest/addons-server#98]
### Describe the problem and steps to reproduce it:
When searching for add-ons within the Thunderbird UI and filtering via "Works with" for my current version, many add-ons that are displayed to be compatible for installation result in a message: "cannot be installed because it is incompatible with Thunderbird <my current version number>"

### What happened?
The add-on could not be installed.

### What did you expect to happen?
The add-on dialog for installation should appear and the add-on should be successfully installed.

### Anything else we should know?
This has been broken on my system for over a year now and the time is overdue to report the problem.
![grafik](https://user-images.githubusercontent.com/6191430/60122478-8dfb1e00-9785-11e9-8c74-506e92f91ad8.png)

**Comment by Sancus** [comment]
This add-on installs fine for me in 60.7.2 so it's really unclear to me what's going on. If you download the XPI, can you install it manually?

**Comment by Sancus** [comment]
Please test this again with an empty profile and no add-ons installed. If that works for you, [you'll want to hit up the support site](https://support.mozilla.org/en-US/products/thunderbird).

**Comment by dryquart** [comment]
I tried installing that add-on from the downloaded file with add-on debugging on and received this message:
_There was an error during installation: Add-on {03B08592-E5B4-45ff-A0BE-C1D975458688} is not compatible with application version. add-on minVersion: 2.0. add-on maxVersion: 3.1a1pre._
So the install button in the TB Add-on UI was redirecting to the wrong add-on version (toolbar_buttons-0.6.0.8-fx+tb+sb)

I downloaded the correct version ... or what I thought was the correct version ... using Firefox, which shows the add-on to be compatible through TB 61.0. The install dialog appeared, but after clicking on the Install button, TB still showed the incompatibility message and the add-on did not install.

The downloaded add-on was toolbar_buttons-1.1-sm+tb+fx, whose rdf-file shows a compatibility from 20.0 to 41.0! 

How were you able to install this add-on.

I will test further with a naked profile.

**Comment by dryquart** [comment]
Note: This add-on is not an isolated case. I just tried another add-on, filtering again for TB version up to 61.0
![grafik](https://user-images.githubusercontent.com/6191430/60130855-5fd30980-9798-11e9-9b6e-14ccaaaa53f0.png)
The Add to TB button directs to _confirm-address-1.2.4-tb_ which is not the most recent version and does not install. Downloading _confirm_address-1.3.2-sm+tb_ does install correctly!

**Comment by Sancus** [comment]
rdf compatibility is overriden by versioncheck.addons.thunderbird.net when any add-on stored on ATN is installed. That is how authors can change the compatibility for their add-on without uploading a new one. So the value stored in the XPI doesn't really matter.

**Comment by Sancus** [comment]
> Note: This add-on is not an isolated case. I just tried another add-on, filtering again for TB version up to 61.0

Sorry, what do you mean by "filtering for TB version up to 61.0" -- there is no reason to change filtering settings, and 61.0 should not even be offered in the filter at all if you are on 60.7.2.

Here is what I see when I search: 
![image](https://user-images.githubusercontent.com/479671/60132739-f8de3200-9750-11e9-9e2b-2b2437727048.png)

You are really seeing this behaviour with a blank profile and no add-ons installed? I cannot replicate any of this behaviour on 60.7.2, and it cannot be widespread or we would be having hundreds of reports.

**Comment by dryquart** [comment]
> Sorry, what do you mean by "filtering for TB version up to 61.0" -- there is no reason to change filtering settings, and 61.0 should not even be offered in the filter at all if you are on 60.7.2.
You are correct. Without filtering, add-ons that are not compatible are grayed out, making installation not possible, but the ones not grayed out do not install anyway due to incompatibility. So I set the filter for troubleshooting purposes only because not filtering gave me the incompatibility error. This did not improve the results.
>You are really seeing this behaviour with a blank profile and no add-ons installed?
I just tested this. The good news for TB: No! The behavior does not replicate on a blank profile (should have thought of that before posting :-( sorry). So the user profile is botched up in some way, possibly by other add-ons. I will test that next, but for now, this is clearly a user-profile issue.

Thanks for the quick responses! :-)

**Comment by Sancus** [comment]
> I just tested this. The good news for TB: No! The behavior does not replicate on a blank profile (should have thought of that before posting :-( sorry). So the user profile is botched up in some way, possibly by other add-ons. I will test that next, but for now, this is clearly a user-profile issue.
> 
> Thanks for the quick responses! :-)

No problem. I'm very sensitive to bugs on the site that could affect everyone. Since this is a profile issue, 
[I'm going to refer you to the support site](https://support.mozilla.org/en-US/questions/new/thunderbird) if you can't figure out the issue on your own.

I will give some generic advice though: First remove/disable all add-ons and restart, and maybe check that there's no `general.useragent.override` pref set, as it could be confusing ATN. Your useragent needs to be the default Thunderbird one.

If that doesn't work, and your email is all IMAP, you could always just rebuild your profile and redownload mail. I realize that sucks and is a pain, but it's a fairly guaranteed way to resolve any issues with old profiles.

I'm going to close the issue here, good luck resolving it on your end.

**Comment by dryquart** [comment]
> check that there's no general.useragent.override pref set,

Bingo! No idea how that got changed.
